package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acknowledges generated by hbm2java
 */
@Entity
@Table(name = "acknowledges", catalog = "skycloud")
public class Acknowledges implements java.io.Serializable {

	private long acknowledgeid;
	private Events events;
	private Users users;
	private int clock;
	private String message;

	public Acknowledges() {
	}

	public Acknowledges(long acknowledgeid, Events events, Users users, int clock, String message) {
		this.acknowledgeid = acknowledgeid;
		this.events = events;
		this.users = users;
		this.clock = clock;
		this.message = message;
	}

	@Id
	@Column(name = "acknowledgeid", unique = true, nullable = false)
	public long getAcknowledgeid() {
		return this.acknowledgeid;
	}

	public void setAcknowledgeid(long acknowledgeid) {
		this.acknowledgeid = acknowledgeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventid", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
