package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(name = "actions", catalog = "skycloud")
public class Actions implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -8340101963092227547L;
	private long actionid;
	private String name;
	private int eventsource;
	private int evaltype;
	private int status;
	private int escPeriod;
	private String defShortdata;
	private String defLongdata;
	private int recoveryMsg;
	private String RShortdata;
	private String RLongdata;
	private Set<Operations> operationses = new HashSet<Operations>(0);
	private Set<Conditions> conditionses = new HashSet<Conditions>(0);
	private Set<Alerts> alertses = new HashSet<Alerts>(0);

	public Actions() {
	}

	public Actions(long actionid, String name, int eventsource, int evaltype, int status, int escPeriod,
			String defShortdata, String defLongdata, int recoveryMsg, String RShortdata, String RLongdata) {
		this.actionid = actionid;
		this.name = name;
		this.eventsource = eventsource;
		this.evaltype = evaltype;
		this.status = status;
		this.escPeriod = escPeriod;
		this.defShortdata = defShortdata;
		this.defLongdata = defLongdata;
		this.recoveryMsg = recoveryMsg;
		this.RShortdata = RShortdata;
		this.RLongdata = RLongdata;
	}

	public Actions(long actionid, String name, int eventsource, int evaltype, int status, int escPeriod,
			String defShortdata, String defLongdata, int recoveryMsg, String RShortdata, String RLongdata,
			Set<Operations> operationses, Set<Conditions> conditionses, Set<Alerts> alertses) {
		this.actionid = actionid;
		this.name = name;
		this.eventsource = eventsource;
		this.evaltype = evaltype;
		this.status = status;
		this.escPeriod = escPeriod;
		this.defShortdata = defShortdata;
		this.defLongdata = defLongdata;
		this.recoveryMsg = recoveryMsg;
		this.RShortdata = RShortdata;
		this.RLongdata = RLongdata;
		this.operationses = operationses;
		this.conditionses = conditionses;
		this.alertses = alertses;
	}

	@Id
	@Column(name = "actionid", unique = true, nullable = false)
	public long getActionid() {
		return this.actionid;
	}

	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "eventsource", nullable = false)
	public int getEventsource() {
		return this.eventsource;
	}

	public void setEventsource(int eventsource) {
		this.eventsource = eventsource;
	}

	@Column(name = "evaltype", nullable = false)
	public int getEvaltype() {
		return this.evaltype;
	}

	public void setEvaltype(int evaltype) {
		this.evaltype = evaltype;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "esc_period", nullable = false)
	public int getEscPeriod() {
		return this.escPeriod;
	}

	public void setEscPeriod(int escPeriod) {
		this.escPeriod = escPeriod;
	}

	@Column(name = "def_shortdata", nullable = false)
	public String getDefShortdata() {
		return this.defShortdata;
	}

	public void setDefShortdata(String defShortdata) {
		this.defShortdata = defShortdata;
	}

	@Column(name = "def_longdata", nullable = false, length = 65535)
	public String getDefLongdata() {
		return this.defLongdata;
	}

	public void setDefLongdata(String defLongdata) {
		this.defLongdata = defLongdata;
	}

	@Column(name = "recovery_msg", nullable = false)
	public int getRecoveryMsg() {
		return this.recoveryMsg;
	}

	public void setRecoveryMsg(int recoveryMsg) {
		this.recoveryMsg = recoveryMsg;
	}

	@Column(name = "r_shortdata", nullable = false)
	public String getRShortdata() {
		return this.RShortdata;
	}

	public void setRShortdata(String RShortdata) {
		this.RShortdata = RShortdata;
	}

	@Column(name = "r_longdata", nullable = false, length = 65535)
	public String getRLongdata() {
		return this.RLongdata;
	}

	public void setRLongdata(String RLongdata) {
		this.RLongdata = RLongdata;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actions")
	public Set<Operations> getOperationses() {
		return this.operationses;
	}

	public void setOperationses(Set<Operations> operationses) {
		this.operationses = operationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actions")
	public Set<Conditions> getConditionses() {
		return this.conditionses;
	}

	public void setConditionses(Set<Conditions> conditionses) {
		this.conditionses = conditionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actions")
	public Set<Alerts> getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set<Alerts> alertses) {
		this.alertses = alertses;
	}

}
