package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alerts generated by hbm2java
 */
@Entity
@Table(name = "alerts", catalog = "skycloud")
public class Alerts implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -2016625284174015062L;
	private long alertid;
	private Events events;
	private Actions actions;
	private Users users;
	private MediaType mediaType;
	private int clock;
	private String sendto;
	private String subject;
	private String message;
	private int status;
	private int retries;
	private String error;
	private int nextcheck;
	private int escStep;
	private int alerttype;
	private Integer my;

	public Alerts() {
	}

	public Alerts(long alertid, Events events, Actions actions, int clock, String sendto, String subject,
			String message, int status, int retries, String error, int nextcheck, int escStep, int alerttype) {
		this.alertid = alertid;
		this.events = events;
		this.actions = actions;
		this.clock = clock;
		this.sendto = sendto;
		this.subject = subject;
		this.message = message;
		this.status = status;
		this.retries = retries;
		this.error = error;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.alerttype = alerttype;
	}

	public Alerts(long alertid, Events events, Actions actions, Users users, MediaType mediaType, int clock,
			String sendto, String subject, String message, int status, int retries, String error, int nextcheck,
			int escStep, int alerttype, Integer my) {
		this.alertid = alertid;
		this.events = events;
		this.actions = actions;
		this.users = users;
		this.mediaType = mediaType;
		this.clock = clock;
		this.sendto = sendto;
		this.subject = subject;
		this.message = message;
		this.status = status;
		this.retries = retries;
		this.error = error;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.alerttype = alerttype;
		this.my = my;
	}

	@Id
	@Column(name = "alertid", unique = true, nullable = false)
	public long getAlertid() {
		return this.alertid;
	}

	public void setAlertid(long alertid) {
		this.alertid = alertid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventid", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actionid", nullable = false)
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mediatypeid")
	public MediaType getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(MediaType mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "sendto", nullable = false, length = 100)
	public String getSendto() {
		return this.sendto;
	}

	public void setSendto(String sendto) {
		this.sendto = sendto;
	}

	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "retries", nullable = false)
	public int getRetries() {
		return this.retries;
	}

	public void setRetries(int retries) {
		this.retries = retries;
	}

	@Column(name = "error", nullable = false, length = 128)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "nextcheck", nullable = false)
	public int getNextcheck() {
		return this.nextcheck;
	}

	public void setNextcheck(int nextcheck) {
		this.nextcheck = nextcheck;
	}

	@Column(name = "esc_step", nullable = false)
	public int getEscStep() {
		return this.escStep;
	}

	public void setEscStep(int escStep) {
		this.escStep = escStep;
	}

	@Column(name = "alerttype", nullable = false)
	public int getAlerttype() {
		return this.alerttype;
	}

	public void setAlerttype(int alerttype) {
		this.alerttype = alerttype;
	}

	@Column(name = "my")
	public Integer getMy() {
		return this.my;
	}

	public void setMy(Integer my) {
		this.my = my;
	}

}
