package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Applications generated by hbm2java
 */
@Entity
@Table(name = "applications", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "hostid",
		"name" }))
public class Applications implements java.io.Serializable {

	private long applicationid;
	private Hosts hosts;
	private Applications applications;
	private String name;
	private Set<Httptest> httptests = new HashSet<Httptest>(0);
	private Set<Applications> applicationses = new HashSet<Applications>(0);
	private Set<ItemsApplications> itemsApplicationses = new HashSet<ItemsApplications>(0);

	public Applications() {
	}

	public Applications(long applicationid, Hosts hosts, String name) {
		this.applicationid = applicationid;
		this.hosts = hosts;
		this.name = name;
	}

	public Applications(long applicationid, Hosts hosts, Applications applications, String name,
			Set<Httptest> httptests, Set<Applications> applicationses, Set<ItemsApplications> itemsApplicationses) {
		this.applicationid = applicationid;
		this.hosts = hosts;
		this.applications = applications;
		this.name = name;
		this.httptests = httptests;
		this.applicationses = applicationses;
		this.itemsApplicationses = itemsApplicationses;
	}

	@Id
	@Column(name = "applicationid", unique = true, nullable = false)
	public long getApplicationid() {
		return this.applicationid;
	}

	public void setApplicationid(long applicationid) {
		this.applicationid = applicationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hostid", nullable = false)
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid")
	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<Httptest> getHttptests() {
		return this.httptests;
	}

	public void setHttptests(Set<Httptest> httptests) {
		this.httptests = httptests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<Applications> getApplicationses() {
		return this.applicationses;
	}

	public void setApplicationses(Set<Applications> applicationses) {
		this.applicationses = applicationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<ItemsApplications> getItemsApplicationses() {
		return this.itemsApplicationses;
	}

	public void setItemsApplicationses(Set<ItemsApplications> itemsApplicationses) {
		this.itemsApplicationses = itemsApplicationses;
	}

}
