package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuditlogDetails generated by hbm2java
 */
@Entity
@Table(name = "auditlog_details", catalog = "skycloud")
public class AuditlogDetails implements java.io.Serializable {

	private long auditdetailid;
	private Auditlog auditlog;
	private String tableName;
	private String fieldName;
	private String oldvalue;
	private String newvalue;

	public AuditlogDetails() {
	}

	public AuditlogDetails(long auditdetailid, Auditlog auditlog, String tableName, String fieldName, String oldvalue,
			String newvalue) {
		this.auditdetailid = auditdetailid;
		this.auditlog = auditlog;
		this.tableName = tableName;
		this.fieldName = fieldName;
		this.oldvalue = oldvalue;
		this.newvalue = newvalue;
	}

	@Id
	@Column(name = "auditdetailid", unique = true, nullable = false)
	public long getAuditdetailid() {
		return this.auditdetailid;
	}

	public void setAuditdetailid(long auditdetailid) {
		this.auditdetailid = auditdetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "auditid", nullable = false)
	public Auditlog getAuditlog() {
		return this.auditlog;
	}

	public void setAuditlog(Auditlog auditlog) {
		this.auditlog = auditlog;
	}

	@Column(name = "table_name", nullable = false, length = 64)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "field_name", nullable = false, length = 64)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "oldvalue", nullable = false, length = 65535)
	public String getOldvalue() {
		return this.oldvalue;
	}

	public void setOldvalue(String oldvalue) {
		this.oldvalue = oldvalue;
	}

	@Column(name = "newvalue", nullable = false, length = 65535)
	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

}
