package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auditlog generated by hbm2java
 */
@Entity
@Table(name = "auditlog", catalog = "skycloud")
public class Auditlog implements java.io.Serializable {

	private long auditid;
	private Users users;
	private int clock;
	private int action;
	private int resourcetype;
	private String details;
	private String ip;
	private long resourceid;
	private String resourcename;
	private Set<AuditlogDetails> auditlogDetailses = new HashSet<AuditlogDetails>(0);

	public Auditlog() {
	}

	public Auditlog(long auditid, Users users, int clock, int action, int resourcetype, String details, String ip,
			long resourceid, String resourcename) {
		this.auditid = auditid;
		this.users = users;
		this.clock = clock;
		this.action = action;
		this.resourcetype = resourcetype;
		this.details = details;
		this.ip = ip;
		this.resourceid = resourceid;
		this.resourcename = resourcename;
	}

	public Auditlog(long auditid, Users users, int clock, int action, int resourcetype, String details, String ip,
			long resourceid, String resourcename, Set<AuditlogDetails> auditlogDetailses) {
		this.auditid = auditid;
		this.users = users;
		this.clock = clock;
		this.action = action;
		this.resourcetype = resourcetype;
		this.details = details;
		this.ip = ip;
		this.resourceid = resourceid;
		this.resourcename = resourcename;
		this.auditlogDetailses = auditlogDetailses;
	}

	@Id
	@Column(name = "auditid", unique = true, nullable = false)
	public long getAuditid() {
		return this.auditid;
	}

	public void setAuditid(long auditid) {
		this.auditid = auditid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "action", nullable = false)
	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

	@Column(name = "resourcetype", nullable = false)
	public int getResourcetype() {
		return this.resourcetype;
	}

	public void setResourcetype(int resourcetype) {
		this.resourcetype = resourcetype;
	}

	@Column(name = "details", nullable = false, length = 128)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "ip", nullable = false, length = 39)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "resourceid", nullable = false)
	public long getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(long resourceid) {
		this.resourceid = resourceid;
	}

	@Column(name = "resourcename", nullable = false)
	public String getResourcename() {
		return this.resourcename;
	}

	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auditlog")
	public Set<AuditlogDetails> getAuditlogDetailses() {
		return this.auditlogDetailses;
	}

	public void setAuditlogDetailses(Set<AuditlogDetails> auditlogDetailses) {
		this.auditlogDetailses = auditlogDetailses;
	}

}
