package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AutoregHost generated by hbm2java
 */
@Entity
@Table(name = "autoreg_host", catalog = "skycloud")
public class AutoregHost implements java.io.Serializable {

	private long autoregHostid;
	private Hosts hosts;
	private String host;
	private String listenIp;
	private int listenPort;
	private String listenDns;

	public AutoregHost() {
	}

	public AutoregHost(long autoregHostid, String host, String listenIp, int listenPort, String listenDns) {
		this.autoregHostid = autoregHostid;
		this.host = host;
		this.listenIp = listenIp;
		this.listenPort = listenPort;
		this.listenDns = listenDns;
	}

	public AutoregHost(long autoregHostid, Hosts hosts, String host, String listenIp, int listenPort, String listenDns) {
		this.autoregHostid = autoregHostid;
		this.hosts = hosts;
		this.host = host;
		this.listenIp = listenIp;
		this.listenPort = listenPort;
		this.listenDns = listenDns;
	}

	@Id
	@Column(name = "autoreg_hostid", unique = true, nullable = false)
	public long getAutoregHostid() {
		return this.autoregHostid;
	}

	public void setAutoregHostid(long autoregHostid) {
		this.autoregHostid = autoregHostid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proxy_hostid")
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@Column(name = "host", nullable = false, length = 64)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "listen_ip", nullable = false, length = 39)
	public String getListenIp() {
		return this.listenIp;
	}

	public void setListenIp(String listenIp) {
		this.listenIp = listenIp;
	}

	@Column(name = "listen_port", nullable = false)
	public int getListenPort() {
		return this.listenPort;
	}

	public void setListenPort(int listenPort) {
		this.listenPort = listenPort;
	}

	@Column(name = "listen_dns", nullable = false, length = 64)
	public String getListenDns() {
		return this.listenDns;
	}

	public void setListenDns(String listenDns) {
		this.listenDns = listenDns;
	}

}
