package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Conditions generated by hbm2java
 */
@Entity
@Table(name = "conditions", catalog = "skycloud")
public class Conditions implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -8983832529547179791L;
	private long conditionid;
	private Actions actions;
	private int conditiontype;
	private int operator;
	private String value;

	public Conditions() {
	}

	public Conditions(long conditionid, Actions actions, int conditiontype, int operator, String value) {
		this.conditionid = conditionid;
		this.actions = actions;
		this.conditiontype = conditiontype;
		this.operator = operator;
		this.value = value;
	}

	@Id
	@Column(name = "conditionid", unique = true, nullable = false)
	public long getConditionid() {
		return this.conditionid;
	}

	public void setConditionid(long conditionid) {
		this.conditionid = conditionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actionid", nullable = false)
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@Column(name = "conditiontype", nullable = false)
	public int getConditiontype() {
		return this.conditiontype;
	}

	public void setConditiontype(int conditiontype) {
		this.conditiontype = conditiontype;
	}

	@Column(name = "operator", nullable = false)
	public int getOperator() {
		return this.operator;
	}

	public void setOperator(int operator) {
		this.operator = operator;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
