package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Drules generated by hbm2java
 */
@Entity
@Table(name = "drules", catalog = "skycloud")
public class Drules implements java.io.Serializable {

	private long druleid;
	private Hosts hosts;
	private String name;
	private String iprange;
	private int delay;
	private int nextcheck;
	private int status;
	private Set<Dhosts> dhostses = new HashSet<Dhosts>(0);
	private Set<Dchecks> dcheckses = new HashSet<Dchecks>(0);

	public Drules() {
	}

	public Drules(long druleid, String name, String iprange, int delay, int nextcheck, int status) {
		this.druleid = druleid;
		this.name = name;
		this.iprange = iprange;
		this.delay = delay;
		this.nextcheck = nextcheck;
		this.status = status;
	}

	public Drules(long druleid, Hosts hosts, String name, String iprange, int delay, int nextcheck, int status,
			Set<Dhosts> dhostses, Set<Dchecks> dcheckses) {
		this.druleid = druleid;
		this.hosts = hosts;
		this.name = name;
		this.iprange = iprange;
		this.delay = delay;
		this.nextcheck = nextcheck;
		this.status = status;
		this.dhostses = dhostses;
		this.dcheckses = dcheckses;
	}

	@Id
	@Column(name = "druleid", unique = true, nullable = false)
	public long getDruleid() {
		return this.druleid;
	}

	public void setDruleid(long druleid) {
		this.druleid = druleid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proxy_hostid")
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iprange", nullable = false)
	public String getIprange() {
		return this.iprange;
	}

	public void setIprange(String iprange) {
		this.iprange = iprange;
	}

	@Column(name = "delay", nullable = false)
	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

	@Column(name = "nextcheck", nullable = false)
	public int getNextcheck() {
		return this.nextcheck;
	}

	public void setNextcheck(int nextcheck) {
		this.nextcheck = nextcheck;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drules")
	public Set<Dhosts> getDhostses() {
		return this.dhostses;
	}

	public void setDhostses(Set<Dhosts> dhostses) {
		this.dhostses = dhostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drules")
	public Set<Dchecks> getDcheckses() {
		return this.dcheckses;
	}

	public void setDcheckses(Set<Dchecks> dcheckses) {
		this.dcheckses = dcheckses;
	}

}
