package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dservices generated by hbm2java
 */
@Entity
@Table(name = "dservices", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "dcheckid",
		"type", "key_", "ip", "port" }))
public class Dservices implements java.io.Serializable {

	private long dserviceid;
	private Dchecks dchecks;
	private Dhosts dhosts;
	private int type;
	private String key;
	private String value;
	private int port;
	private int status;
	private int lastup;
	private int lastdown;
	private String ip;
	private String dns;

	public Dservices() {
	}

	public Dservices(long dserviceid, Dchecks dchecks, Dhosts dhosts, int type, String key, String value, int port,
			int status, int lastup, int lastdown, String ip, String dns) {
		this.dserviceid = dserviceid;
		this.dchecks = dchecks;
		this.dhosts = dhosts;
		this.type = type;
		this.key = key;
		this.value = value;
		this.port = port;
		this.status = status;
		this.lastup = lastup;
		this.lastdown = lastdown;
		this.ip = ip;
		this.dns = dns;
	}

	@Id
	@Column(name = "dserviceid", unique = true, nullable = false)
	public long getDserviceid() {
		return this.dserviceid;
	}

	public void setDserviceid(long dserviceid) {
		this.dserviceid = dserviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dcheckid", nullable = false)
	public Dchecks getDchecks() {
		return this.dchecks;
	}

	public void setDchecks(Dchecks dchecks) {
		this.dchecks = dchecks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dhostid", nullable = false)
	public Dhosts getDhosts() {
		return this.dhosts;
	}

	public void setDhosts(Dhosts dhosts) {
		this.dhosts = dhosts;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "key_", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "lastup", nullable = false)
	public int getLastup() {
		return this.lastup;
	}

	public void setLastup(int lastup) {
		this.lastup = lastup;
	}

	@Column(name = "lastdown", nullable = false)
	public int getLastdown() {
		return this.lastdown;
	}

	public void setLastdown(int lastdown) {
		this.lastdown = lastdown;
	}

	@Column(name = "ip", nullable = false, length = 39)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "dns", nullable = false, length = 64)
	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

}
