package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Escalations generated by hbm2java
 */
@Entity
@Table(name = "escalations", catalog = "skycloud")
public class Escalations implements java.io.Serializable {

	private long escalationid;
	private long actionid;
	private Long triggerid;
	private Long eventid;
	private Long REventid;
	private int nextcheck;
	private int escStep;
	private int status;

	public Escalations() {
	}

	public Escalations(long escalationid, long actionid, int nextcheck, int escStep, int status) {
		this.escalationid = escalationid;
		this.actionid = actionid;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.status = status;
	}

	public Escalations(long escalationid, long actionid, Long triggerid, Long eventid, Long REventid, int nextcheck,
			int escStep, int status) {
		this.escalationid = escalationid;
		this.actionid = actionid;
		this.triggerid = triggerid;
		this.eventid = eventid;
		this.REventid = REventid;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.status = status;
	}

	@Id
	@Column(name = "escalationid", unique = true, nullable = false)
	public long getEscalationid() {
		return this.escalationid;
	}

	public void setEscalationid(long escalationid) {
		this.escalationid = escalationid;
	}

	@Column(name = "actionid", nullable = false)
	public long getActionid() {
		return this.actionid;
	}

	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	@Column(name = "triggerid")
	public Long getTriggerid() {
		return this.triggerid;
	}

	public void setTriggerid(Long triggerid) {
		this.triggerid = triggerid;
	}

	@Column(name = "eventid")
	public Long getEventid() {
		return this.eventid;
	}

	public void setEventid(Long eventid) {
		this.eventid = eventid;
	}

	@Column(name = "r_eventid")
	public Long getREventid() {
		return this.REventid;
	}

	public void setREventid(Long REventid) {
		this.REventid = REventid;
	}

	@Column(name = "nextcheck", nullable = false)
	public int getNextcheck() {
		return this.nextcheck;
	}

	public void setNextcheck(int nextcheck) {
		this.nextcheck = nextcheck;
	}

	@Column(name = "esc_step", nullable = false)
	public int getEscStep() {
		return this.escStep;
	}

	public void setEscStep(int escStep) {
		this.escStep = escStep;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
