package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "skycloud")
public class Events implements java.io.Serializable {

	private long eventid;
	private int source;
	private int object;
	private long objectid;
	private int clock;
	private int value;
	private int acknowledged;
	private int ns;
	private int valueChanged;
	private Integer my;
	private Set<Alerts> alertses = new HashSet<Alerts>(0);
	private Set<Acknowledges> acknowledgeses = new HashSet<Acknowledges>(0);

	public Events() {
	}

	public Events(long eventid, int source, int object, long objectid, int clock, int value, int acknowledged, int ns,
			int valueChanged) {
		this.eventid = eventid;
		this.source = source;
		this.object = object;
		this.objectid = objectid;
		this.clock = clock;
		this.value = value;
		this.acknowledged = acknowledged;
		this.ns = ns;
		this.valueChanged = valueChanged;
	}

	public Events(long eventid, int source, int object, long objectid, int clock, int value, int acknowledged, int ns,
			int valueChanged, Integer my, Set<Alerts> alertses, Set<Acknowledges> acknowledgeses) {
		this.eventid = eventid;
		this.source = source;
		this.object = object;
		this.objectid = objectid;
		this.clock = clock;
		this.value = value;
		this.acknowledged = acknowledged;
		this.ns = ns;
		this.valueChanged = valueChanged;
		this.my = my;
		this.alertses = alertses;
		this.acknowledgeses = acknowledgeses;
	}

	@Id
	@Column(name = "eventid", unique = true, nullable = false)
	public long getEventid() {
		return this.eventid;
	}

	public void setEventid(long eventid) {
		this.eventid = eventid;
	}

	@Column(name = "source", nullable = false)
	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	@Column(name = "object", nullable = false)
	public int getObject() {
		return this.object;
	}

	public void setObject(int object) {
		this.object = object;
	}

	@Column(name = "objectid", nullable = false)
	public long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(long objectid) {
		this.objectid = objectid;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	@Column(name = "acknowledged", nullable = false)
	public int getAcknowledged() {
		return this.acknowledged;
	}

	public void setAcknowledged(int acknowledged) {
		this.acknowledged = acknowledged;
	}

	@Column(name = "ns", nullable = false)
	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	@Column(name = "value_changed", nullable = false)
	public int getValueChanged() {
		return this.valueChanged;
	}

	public void setValueChanged(int valueChanged) {
		this.valueChanged = valueChanged;
	}

	@Column(name = "my")
	public Integer getMy() {
		return this.my;
	}

	public void setMy(Integer my) {
		this.my = my;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "events")
	public Set<Alerts> getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set<Alerts> alertses) {
		this.alertses = alertses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "events")
	public Set<Acknowledges> getAcknowledgeses() {
		return this.acknowledgeses;
	}

	public void setAcknowledgeses(Set<Acknowledges> acknowledgeses) {
		this.acknowledgeses = acknowledgeses;
	}

}
