package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Expressions generated by hbm2java
 */
@Entity
@Table(name = "expressions", catalog = "skycloud")
public class Expressions implements java.io.Serializable {

	private long expressionid;
	private Regexps regexps;
	private String expression;
	private int expressionType;
	private String expDelimiter;
	private int caseSensitive;

	public Expressions() {
	}

	public Expressions(long expressionid, Regexps regexps, String expression, int expressionType, String expDelimiter,
			int caseSensitive) {
		this.expressionid = expressionid;
		this.regexps = regexps;
		this.expression = expression;
		this.expressionType = expressionType;
		this.expDelimiter = expDelimiter;
		this.caseSensitive = caseSensitive;
	}

	@Id
	@Column(name = "expressionid", unique = true, nullable = false)
	public long getExpressionid() {
		return this.expressionid;
	}

	public void setExpressionid(long expressionid) {
		this.expressionid = expressionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regexpid", nullable = false)
	public Regexps getRegexps() {
		return this.regexps;
	}

	public void setRegexps(Regexps regexps) {
		this.regexps = regexps;
	}

	@Column(name = "expression", nullable = false)
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "expression_type", nullable = false)
	public int getExpressionType() {
		return this.expressionType;
	}

	public void setExpressionType(int expressionType) {
		this.expressionType = expressionType;
	}

	@Column(name = "exp_delimiter", nullable = false, length = 1)
	public String getExpDelimiter() {
		return this.expDelimiter;
	}

	public void setExpDelimiter(String expDelimiter) {
		this.expDelimiter = expDelimiter;
	}

	@Column(name = "case_sensitive", nullable = false)
	public int getCaseSensitive() {
		return this.caseSensitive;
	}

	public void setCaseSensitive(int caseSensitive) {
		this.caseSensitive = caseSensitive;
	}

}
