package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Functions generated by hbm2java
 */
@Entity
@Table(name = "functions", catalog = "skycloud")
public class Functions implements java.io.Serializable {

	private long functionid;
	private Triggers triggers;
	private Items items;
	private String function;
	private String parameter;

	public Functions() {
	}

	public Functions(long functionid, Triggers triggers, Items items, String function, String parameter) {
		this.functionid = functionid;
		this.triggers = triggers;
		this.items = items;
		this.function = function;
		this.parameter = parameter;
	}

	@Id
	@Column(name = "functionid", unique = true, nullable = false)
	public long getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(long functionid) {
		this.functionid = functionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "triggerid", nullable = false)
	public Triggers getTriggers() {
		return this.triggers;
	}

	public void setTriggers(Triggers triggers) {
		this.triggers = triggers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "function", nullable = false, length = 12)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "parameter", nullable = false)
	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

}
