package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Globalmacro generated by hbm2java
 */
@Entity
@Table(name = "globalmacro", catalog = "skycloud")
public class Globalmacro implements java.io.Serializable {

	private long globalmacroid;
	private String macro;
	private String value;

	public Globalmacro() {
	}

	public Globalmacro(long globalmacroid, String macro, String value) {
		this.globalmacroid = globalmacroid;
		this.macro = macro;
		this.value = value;
	}

	@Id
	@Column(name = "globalmacroid", unique = true, nullable = false)
	public long getGlobalmacroid() {
		return this.globalmacroid;
	}

	public void setGlobalmacroid(long globalmacroid) {
		this.globalmacroid = globalmacroid;
	}

	@Column(name = "macro", nullable = false, length = 64)
	public String getMacro() {
		return this.macro;
	}

	public void setMacro(String macro) {
		this.macro = macro;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
