package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GraphTheme generated by hbm2java
 */
@Entity
@Table(name = "graph_theme", catalog = "skycloud")
public class GraphTheme implements java.io.Serializable {

	private long graphthemeid;
	private String description;
	private String theme;
	private String backgroundcolor;
	private String graphcolor;
	private String graphbordercolor;
	private String gridcolor;
	private String maingridcolor;
	private String gridbordercolor;
	private String textcolor;
	private String highlightcolor;
	private String leftpercentilecolor;
	private String rightpercentilecolor;
	private String nonworktimecolor;
	private int gridview;
	private int legendview;

	public GraphTheme() {
	}

	public GraphTheme(long graphthemeid, String description, String theme, String backgroundcolor, String graphcolor,
			String graphbordercolor, String gridcolor, String maingridcolor, String gridbordercolor, String textcolor,
			String highlightcolor, String leftpercentilecolor, String rightpercentilecolor, String nonworktimecolor,
			int gridview, int legendview) {
		this.graphthemeid = graphthemeid;
		this.description = description;
		this.theme = theme;
		this.backgroundcolor = backgroundcolor;
		this.graphcolor = graphcolor;
		this.graphbordercolor = graphbordercolor;
		this.gridcolor = gridcolor;
		this.maingridcolor = maingridcolor;
		this.gridbordercolor = gridbordercolor;
		this.textcolor = textcolor;
		this.highlightcolor = highlightcolor;
		this.leftpercentilecolor = leftpercentilecolor;
		this.rightpercentilecolor = rightpercentilecolor;
		this.nonworktimecolor = nonworktimecolor;
		this.gridview = gridview;
		this.legendview = legendview;
	}

	@Id
	@Column(name = "graphthemeid", unique = true, nullable = false)
	public long getGraphthemeid() {
		return this.graphthemeid;
	}

	public void setGraphthemeid(long graphthemeid) {
		this.graphthemeid = graphthemeid;
	}

	@Column(name = "description", nullable = false, length = 64)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "theme", nullable = false, length = 64)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "backgroundcolor", nullable = false, length = 6)
	public String getBackgroundcolor() {
		return this.backgroundcolor;
	}

	public void setBackgroundcolor(String backgroundcolor) {
		this.backgroundcolor = backgroundcolor;
	}

	@Column(name = "graphcolor", nullable = false, length = 6)
	public String getGraphcolor() {
		return this.graphcolor;
	}

	public void setGraphcolor(String graphcolor) {
		this.graphcolor = graphcolor;
	}

	@Column(name = "graphbordercolor", nullable = false, length = 6)
	public String getGraphbordercolor() {
		return this.graphbordercolor;
	}

	public void setGraphbordercolor(String graphbordercolor) {
		this.graphbordercolor = graphbordercolor;
	}

	@Column(name = "gridcolor", nullable = false, length = 6)
	public String getGridcolor() {
		return this.gridcolor;
	}

	public void setGridcolor(String gridcolor) {
		this.gridcolor = gridcolor;
	}

	@Column(name = "maingridcolor", nullable = false, length = 6)
	public String getMaingridcolor() {
		return this.maingridcolor;
	}

	public void setMaingridcolor(String maingridcolor) {
		this.maingridcolor = maingridcolor;
	}

	@Column(name = "gridbordercolor", nullable = false, length = 6)
	public String getGridbordercolor() {
		return this.gridbordercolor;
	}

	public void setGridbordercolor(String gridbordercolor) {
		this.gridbordercolor = gridbordercolor;
	}

	@Column(name = "textcolor", nullable = false, length = 6)
	public String getTextcolor() {
		return this.textcolor;
	}

	public void setTextcolor(String textcolor) {
		this.textcolor = textcolor;
	}

	@Column(name = "highlightcolor", nullable = false, length = 6)
	public String getHighlightcolor() {
		return this.highlightcolor;
	}

	public void setHighlightcolor(String highlightcolor) {
		this.highlightcolor = highlightcolor;
	}

	@Column(name = "leftpercentilecolor", nullable = false, length = 6)
	public String getLeftpercentilecolor() {
		return this.leftpercentilecolor;
	}

	public void setLeftpercentilecolor(String leftpercentilecolor) {
		this.leftpercentilecolor = leftpercentilecolor;
	}

	@Column(name = "rightpercentilecolor", nullable = false, length = 6)
	public String getRightpercentilecolor() {
		return this.rightpercentilecolor;
	}

	public void setRightpercentilecolor(String rightpercentilecolor) {
		this.rightpercentilecolor = rightpercentilecolor;
	}

	@Column(name = "nonworktimecolor", nullable = false, length = 6)
	public String getNonworktimecolor() {
		return this.nonworktimecolor;
	}

	public void setNonworktimecolor(String nonworktimecolor) {
		this.nonworktimecolor = nonworktimecolor;
	}

	@Column(name = "gridview", nullable = false)
	public int getGridview() {
		return this.gridview;
	}

	public void setGridview(int gridview) {
		this.gridview = gridview;
	}

	@Column(name = "legendview", nullable = false)
	public int getLegendview() {
		return this.legendview;
	}

	public void setLegendview(int legendview) {
		this.legendview = legendview;
	}

}
