package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Graphs generated by hbm2java
 */
@Entity
@Table(name = "graphs", catalog = "skycloud")
public class Graphs implements java.io.Serializable {

	private long graphid;
	private Items itemsByYmaxItemid;
	private Graphs graphs;
	private Items itemsByYminItemid;
	private String name;
	private int width;
	private int height;
	private double yaxismin;
	private double yaxismax;
	private int showWorkPeriod;
	private int showTriggers;
	private int graphtype;
	private int showLegend;
	private int show3d;
	private double percentLeft;
	private double percentRight;
	private int yminType;
	private int ymaxType;
	private int flags;
	private Set<GraphDiscovery> graphDiscoveriesForGraphid = new HashSet<GraphDiscovery>(0);
	private Set<Graphs> graphses = new HashSet<Graphs>(0);
	private Set<GraphDiscovery> graphDiscoveriesForParentGraphid = new HashSet<GraphDiscovery>(0);
	private Set<GraphsItems> graphsItemses = new HashSet<GraphsItems>(0);

	public Graphs() {
	}

	public Graphs(long graphid, String name, int width, int height, double yaxismin, double yaxismax,
			int showWorkPeriod, int showTriggers, int graphtype, int showLegend, int show3d, double percentLeft,
			double percentRight, int yminType, int ymaxType, int flags) {
		this.graphid = graphid;
		this.name = name;
		this.width = width;
		this.height = height;
		this.yaxismin = yaxismin;
		this.yaxismax = yaxismax;
		this.showWorkPeriod = showWorkPeriod;
		this.showTriggers = showTriggers;
		this.graphtype = graphtype;
		this.showLegend = showLegend;
		this.show3d = show3d;
		this.percentLeft = percentLeft;
		this.percentRight = percentRight;
		this.yminType = yminType;
		this.ymaxType = ymaxType;
		this.flags = flags;
	}

	public Graphs(long graphid, Items itemsByYmaxItemid, Graphs graphs, Items itemsByYminItemid, String name,
			int width, int height, double yaxismin, double yaxismax, int showWorkPeriod, int showTriggers,
			int graphtype, int showLegend, int show3d, double percentLeft, double percentRight, int yminType,
			int ymaxType, int flags, Set<GraphDiscovery> graphDiscoveriesForGraphid, Set<Graphs> graphses,
			Set<GraphDiscovery> graphDiscoveriesForParentGraphid, Set<GraphsItems> graphsItemses) {
		this.graphid = graphid;
		this.itemsByYmaxItemid = itemsByYmaxItemid;
		this.graphs = graphs;
		this.itemsByYminItemid = itemsByYminItemid;
		this.name = name;
		this.width = width;
		this.height = height;
		this.yaxismin = yaxismin;
		this.yaxismax = yaxismax;
		this.showWorkPeriod = showWorkPeriod;
		this.showTriggers = showTriggers;
		this.graphtype = graphtype;
		this.showLegend = showLegend;
		this.show3d = show3d;
		this.percentLeft = percentLeft;
		this.percentRight = percentRight;
		this.yminType = yminType;
		this.ymaxType = ymaxType;
		this.flags = flags;
		this.graphDiscoveriesForGraphid = graphDiscoveriesForGraphid;
		this.graphses = graphses;
		this.graphDiscoveriesForParentGraphid = graphDiscoveriesForParentGraphid;
		this.graphsItemses = graphsItemses;
	}

	@Id
	@Column(name = "graphid", unique = true, nullable = false)
	public long getGraphid() {
		return this.graphid;
	}

	public void setGraphid(long graphid) {
		this.graphid = graphid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ymax_itemid")
	public Items getItemsByYmaxItemid() {
		return this.itemsByYmaxItemid;
	}

	public void setItemsByYmaxItemid(Items itemsByYmaxItemid) {
		this.itemsByYmaxItemid = itemsByYmaxItemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid")
	public Graphs getGraphs() {
		return this.graphs;
	}

	public void setGraphs(Graphs graphs) {
		this.graphs = graphs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ymin_itemid")
	public Items getItemsByYminItemid() {
		return this.itemsByYminItemid;
	}

	public void setItemsByYminItemid(Items itemsByYminItemid) {
		this.itemsByYminItemid = itemsByYminItemid;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "width", nullable = false)
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "yaxismin", nullable = false, precision = 16, scale = 4)
	public double getYaxismin() {
		return this.yaxismin;
	}

	public void setYaxismin(double yaxismin) {
		this.yaxismin = yaxismin;
	}

	@Column(name = "yaxismax", nullable = false, precision = 16, scale = 4)
	public double getYaxismax() {
		return this.yaxismax;
	}

	public void setYaxismax(double yaxismax) {
		this.yaxismax = yaxismax;
	}

	@Column(name = "show_work_period", nullable = false)
	public int getShowWorkPeriod() {
		return this.showWorkPeriod;
	}

	public void setShowWorkPeriod(int showWorkPeriod) {
		this.showWorkPeriod = showWorkPeriod;
	}

	@Column(name = "show_triggers", nullable = false)
	public int getShowTriggers() {
		return this.showTriggers;
	}

	public void setShowTriggers(int showTriggers) {
		this.showTriggers = showTriggers;
	}

	@Column(name = "graphtype", nullable = false)
	public int getGraphtype() {
		return this.graphtype;
	}

	public void setGraphtype(int graphtype) {
		this.graphtype = graphtype;
	}

	@Column(name = "show_legend", nullable = false)
	public int getShowLegend() {
		return this.showLegend;
	}

	public void setShowLegend(int showLegend) {
		this.showLegend = showLegend;
	}

	@Column(name = "show_3d", nullable = false)
	public int getShow3d() {
		return this.show3d;
	}

	public void setShow3d(int show3d) {
		this.show3d = show3d;
	}

	@Column(name = "percent_left", nullable = false, precision = 16, scale = 4)
	public double getPercentLeft() {
		return this.percentLeft;
	}

	public void setPercentLeft(double percentLeft) {
		this.percentLeft = percentLeft;
	}

	@Column(name = "percent_right", nullable = false, precision = 16, scale = 4)
	public double getPercentRight() {
		return this.percentRight;
	}

	public void setPercentRight(double percentRight) {
		this.percentRight = percentRight;
	}

	@Column(name = "ymin_type", nullable = false)
	public int getYminType() {
		return this.yminType;
	}

	public void setYminType(int yminType) {
		this.yminType = yminType;
	}

	@Column(name = "ymax_type", nullable = false)
	public int getYmaxType() {
		return this.ymaxType;
	}

	public void setYmaxType(int ymaxType) {
		this.ymaxType = ymaxType;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graphsByGraphid")
	public Set<GraphDiscovery> getGraphDiscoveriesForGraphid() {
		return this.graphDiscoveriesForGraphid;
	}

	public void setGraphDiscoveriesForGraphid(Set<GraphDiscovery> graphDiscoveriesForGraphid) {
		this.graphDiscoveriesForGraphid = graphDiscoveriesForGraphid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graphs")
	public Set<Graphs> getGraphses() {
		return this.graphses;
	}

	public void setGraphses(Set<Graphs> graphses) {
		this.graphses = graphses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graphsByParentGraphid")
	public Set<GraphDiscovery> getGraphDiscoveriesForParentGraphid() {
		return this.graphDiscoveriesForParentGraphid;
	}

	public void setGraphDiscoveriesForParentGraphid(Set<GraphDiscovery> graphDiscoveriesForParentGraphid) {
		this.graphDiscoveriesForParentGraphid = graphDiscoveriesForParentGraphid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graphs")
	public Set<GraphsItems> getGraphsItemses() {
		return this.graphsItemses;
	}

	public void setGraphsItemses(Set<GraphsItems> graphsItemses) {
		this.graphsItemses = graphsItemses;
	}

}
