package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GraphDiscovery generated by hbm2java
 */
@Entity
@Table(name = "graph_discovery", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "graphid",
		"parent_graphid" }))
public class GraphDiscovery implements java.io.Serializable {

	private long graphdiscoveryid;
	private Graphs graphsByParentGraphid;
	private Graphs graphsByGraphid;
	private String name;

	public GraphDiscovery() {
	}

	public GraphDiscovery(long graphdiscoveryid, Graphs graphsByParentGraphid, Graphs graphsByGraphid, String name) {
		this.graphdiscoveryid = graphdiscoveryid;
		this.graphsByParentGraphid = graphsByParentGraphid;
		this.graphsByGraphid = graphsByGraphid;
		this.name = name;
	}

	@Id
	@Column(name = "graphdiscoveryid", unique = true, nullable = false)
	public long getGraphdiscoveryid() {
		return this.graphdiscoveryid;
	}

	public void setGraphdiscoveryid(long graphdiscoveryid) {
		this.graphdiscoveryid = graphdiscoveryid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_graphid", nullable = false)
	public Graphs getGraphsByParentGraphid() {
		return this.graphsByParentGraphid;
	}

	public void setGraphsByParentGraphid(Graphs graphsByParentGraphid) {
		this.graphsByParentGraphid = graphsByParentGraphid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "graphid", nullable = false)
	public Graphs getGraphsByGraphid() {
		return this.graphsByGraphid;
	}

	public void setGraphsByGraphid(Graphs graphsByGraphid) {
		this.graphsByGraphid = graphsByGraphid;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
