package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "skycloud")
public class Groups implements java.io.Serializable {

	private long groupid;
	private String name;
	private int internal;
	private Set<Rights> rightses = new HashSet<Rights>(0);
	private Set<OpcommandGrp> opcommandGrps = new HashSet<OpcommandGrp>(0);
	private Set<HostsGroups> hostsGroupses = new HashSet<HostsGroups>(0);
	private Set<Config> configs = new HashSet<Config>(0);
	private Set<MaintenancesGroups> maintenancesGroupses = new HashSet<MaintenancesGroups>(0);
	private Set<Scripts> scriptses = new HashSet<Scripts>(0);
	private Set<Opgroup> opgroups = new HashSet<Opgroup>(0);

	public Groups() {
	}

	public Groups(long groupid, String name, int internal) {
		this.groupid = groupid;
		this.name = name;
		this.internal = internal;
	}

	public Groups(long groupid, String name, int internal, Set<Rights> rightses, Set<OpcommandGrp> opcommandGrps,
			Set<HostsGroups> hostsGroupses, Set<Config> configs, Set<MaintenancesGroups> maintenancesGroupses,
			Set<Scripts> scriptses, Set<Opgroup> opgroups) {
		this.groupid = groupid;
		this.name = name;
		this.internal = internal;
		this.rightses = rightses;
		this.opcommandGrps = opcommandGrps;
		this.hostsGroupses = hostsGroupses;
		this.configs = configs;
		this.maintenancesGroupses = maintenancesGroupses;
		this.scriptses = scriptses;
		this.opgroups = opgroups;
	}

	@Id
	@Column(name = "groupid", unique = true, nullable = false)
	public long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(long groupid) {
		this.groupid = groupid;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "internal", nullable = false)
	public int getInternal() {
		return this.internal;
	}

	public void setInternal(int internal) {
		this.internal = internal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Rights> getRightses() {
		return this.rightses;
	}

	public void setRightses(Set<Rights> rightses) {
		this.rightses = rightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<OpcommandGrp> getOpcommandGrps() {
		return this.opcommandGrps;
	}

	public void setOpcommandGrps(Set<OpcommandGrp> opcommandGrps) {
		this.opcommandGrps = opcommandGrps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<HostsGroups> getHostsGroupses() {
		return this.hostsGroupses;
	}

	public void setHostsGroupses(Set<HostsGroups> hostsGroupses) {
		this.hostsGroupses = hostsGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Config> getConfigs() {
		return this.configs;
	}

	public void setConfigs(Set<Config> configs) {
		this.configs = configs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<MaintenancesGroups> getMaintenancesGroupses() {
		return this.maintenancesGroupses;
	}

	public void setMaintenancesGroupses(Set<MaintenancesGroups> maintenancesGroupses) {
		this.maintenancesGroupses = maintenancesGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Scripts> getScriptses() {
		return this.scriptses;
	}

	public void setScriptses(Set<Scripts> scriptses) {
		this.scriptses = scriptses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Opgroup> getOpgroups() {
		return this.opgroups;
	}

	public void setOpgroups(Set<Opgroup> opgroups) {
		this.opgroups = opgroups;
	}

}
