package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HelpItems generated by hbm2java
 */
@Entity
@Table(name = "help_items", catalog = "skycloud")
public class HelpItems implements java.io.Serializable {

	private HelpItemsId id;
	private String description;

	public HelpItems() {
	}

	public HelpItems(HelpItemsId id, String description) {
		this.id = id;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "itemtype", column = @Column(name = "itemtype", nullable = false)),
			@AttributeOverride(name = "key", column = @Column(name = "key_", nullable = false)) })
	public HelpItemsId getId() {
		return this.id;
	}

	public void setId(HelpItemsId id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
