package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HelpItemsId generated by hbm2java
 */
@Embeddable
public class HelpItemsId implements java.io.Serializable {

	private int itemtype;
	private String key;

	public HelpItemsId() {
	}

	public HelpItemsId(int itemtype, String key) {
		this.itemtype = itemtype;
		this.key = key;
	}

	@Column(name = "itemtype", nullable = false)
	public int getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(int itemtype) {
		this.itemtype = itemtype;
	}

	@Column(name = "key_", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HelpItemsId))
			return false;
		HelpItemsId castOther = (HelpItemsId) other;

		return (this.getItemtype() == castOther.getItemtype())
				&& ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
						.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemtype();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
