package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistoryStrId generated by hbm2java
 */
@Embeddable
public class HistoryStrId implements java.io.Serializable {

	private long itemid;
	private int clock;
	private String value;
	private int ns;

	public HistoryStrId() {
	}

	public HistoryStrId(long itemid, int clock, String value, int ns) {
		this.itemid = itemid;
		this.clock = clock;
		this.value = value;
		this.ns = ns;
	}

	@Column(name = "itemid", nullable = false)
	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ns", nullable = false)
	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryStrId))
			return false;
		HistoryStrId castOther = (HistoryStrId) other;

		return (this.getItemid() == castOther.getItemid())
				&& (this.getClock() == castOther.getClock())
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& (this.getNs() == castOther.getNs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemid();
		result = 37 * result + this.getClock();
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + this.getNs();
		return result;
	}

}
