package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistoryUintId generated by hbm2java
 */
@Embeddable
public class HistoryUintId implements java.io.Serializable {

	private long itemid;
	private int clock;
	private long value;
	private int ns;

	public HistoryUintId() {
	}

	public HistoryUintId(long itemid, int clock, long value, int ns) {
		this.itemid = itemid;
		this.clock = clock;
		this.value = value;
		this.ns = ns;
	}

	@Column(name = "itemid", nullable = false)
	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "value", nullable = false)
	public long getValue() {
		return this.value;
	}

	public void setValue(long value) {
		this.value = value;
	}

	@Column(name = "ns", nullable = false)
	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryUintId))
			return false;
		HistoryUintId castOther = (HistoryUintId) other;

		return (this.getItemid() == castOther.getItemid()) && (this.getClock() == castOther.getClock())
				&& (this.getValue() == castOther.getValue()) && (this.getNs() == castOther.getNs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemid();
		result = 37 * result + this.getClock();
		result = 37 * result + (int) this.getValue();
		result = 37 * result + this.getNs();
		return result;
	}

}
