package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Hosts generated by hbm2java
 */
@Entity
@Table(name = "hosts", catalog = "skycloud")
public class Hosts implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -360348502143732897L;
	private Long hostid;
	private Maintenances maintenances;
	private Hosts hosts;
	private String host;
	private Integer status;
	private int disableUntil;
	private String error;
	private int available;
	private int errorsFrom;
	private int lastaccess;
	private int ipmiAuthtype;
	private int ipmiPrivilege;
	private String ipmiUsername;
	private String ipmiPassword;
	private int ipmiDisableUntil;
	private int ipmiAvailable;
	private int snmpDisableUntil;
	private int snmpAvailable;
	private int maintenanceStatus;
	private int maintenanceType;
	private int maintenanceFrom;
	private int ipmiErrorsFrom;
	private int snmpErrorsFrom;
	private String ipmiError;
	private String snmpError;
	private int jmxDisableUntil;
	private int jmxAvailable;
	private int jmxErrorsFrom;
	private String jmxError;
	private String name;
	private Set<MaintenancesHosts> maintenancesHostses = new HashSet<MaintenancesHosts>(0);
	private Set<Screens> screenses = new HashSet<Screens>(0);
	private Set<OpcommandHst> opcommandHsts = new HashSet<OpcommandHst>(0);
	private Set<HostsTemplates> hostsTemplatesesForHostid = new HashSet<HostsTemplates>(0);
	private Set<HostsTemplates> hostsTemplatesesForTemplateid = new HashSet<HostsTemplates>(0);
	private Set<Drules> druleses = new HashSet<Drules>(0);
	private Set<Hostmacro> hostmacros = new HashSet<Hostmacro>(0);
	private Set<Optemplate> optemplates = new HashSet<Optemplate>(0);
	private HostInventory hostInventory;
	private Set<Applications> applicationses = new HashSet<Applications>(0);
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<AutoregHost> autoregHosts = new HashSet<AutoregHost>(0);
	private Set<Interfaces> interfaceses = new HashSet<Interfaces>(0);
	private Set<HostsGroups> hostsGroupses = new HashSet<HostsGroups>(0);
	private Set<Hosts> hostses = new HashSet<Hosts>(0);

	public Hosts() {
	}

	public Hosts(Long hostid, String host, Integer status, int disableUntil, String error, int available,
			int errorsFrom, int lastaccess, int ipmiAuthtype, int ipmiPrivilege, String ipmiUsername,
			String ipmiPassword, int ipmiDisableUntil, int ipmiAvailable, int snmpDisableUntil, int snmpAvailable,
			int maintenanceStatus, int maintenanceType, int maintenanceFrom, int ipmiErrorsFrom, int snmpErrorsFrom,
			String ipmiError, String snmpError, int jmxDisableUntil, int jmxAvailable, int jmxErrorsFrom,
			String jmxError, String name) {
		this.hostid = hostid;
		this.host = host;
		this.status = status;
		this.disableUntil = disableUntil;
		this.error = error;
		this.available = available;
		this.errorsFrom = errorsFrom;
		this.lastaccess = lastaccess;
		this.ipmiAuthtype = ipmiAuthtype;
		this.ipmiPrivilege = ipmiPrivilege;
		this.ipmiUsername = ipmiUsername;
		this.ipmiPassword = ipmiPassword;
		this.ipmiDisableUntil = ipmiDisableUntil;
		this.ipmiAvailable = ipmiAvailable;
		this.snmpDisableUntil = snmpDisableUntil;
		this.snmpAvailable = snmpAvailable;
		this.maintenanceStatus = maintenanceStatus;
		this.maintenanceType = maintenanceType;
		this.maintenanceFrom = maintenanceFrom;
		this.ipmiErrorsFrom = ipmiErrorsFrom;
		this.snmpErrorsFrom = snmpErrorsFrom;
		this.ipmiError = ipmiError;
		this.snmpError = snmpError;
		this.jmxDisableUntil = jmxDisableUntil;
		this.jmxAvailable = jmxAvailable;
		this.jmxErrorsFrom = jmxErrorsFrom;
		this.jmxError = jmxError;
		this.name = name;
	}

	public Hosts(Long hostid, Maintenances maintenances, Hosts hosts, String host, Integer status, int disableUntil,
			String error, int available, int errorsFrom, int lastaccess, int ipmiAuthtype, int ipmiPrivilege,
			String ipmiUsername, String ipmiPassword, int ipmiDisableUntil, int ipmiAvailable, int snmpDisableUntil,
			int snmpAvailable, int maintenanceStatus, int maintenanceType, int maintenanceFrom, int ipmiErrorsFrom,
			int snmpErrorsFrom, String ipmiError, String snmpError, int jmxDisableUntil, int jmxAvailable,
			int jmxErrorsFrom, String jmxError, String name, Set<MaintenancesHosts> maintenancesHostses,
			Set<Screens> screenses, Set<OpcommandHst> opcommandHsts, Set<HostsTemplates> hostsTemplatesesForHostid,
			Set<HostsTemplates> hostsTemplatesesForTemplateid, Set<Drules> druleses, Set<Hostmacro> hostmacros,
			Set<Optemplate> optemplates, HostInventory hostInventory, Set<Applications> applicationses,
			Set<Items> itemses, Set<AutoregHost> autoregHosts, Set<Interfaces> interfaceses,
			Set<HostsGroups> hostsGroupses, Set<Hosts> hostses) {
		this.hostid = hostid;
		this.maintenances = maintenances;
		this.hosts = hosts;
		this.host = host;
		this.status = status;
		this.disableUntil = disableUntil;
		this.error = error;
		this.available = available;
		this.errorsFrom = errorsFrom;
		this.lastaccess = lastaccess;
		this.ipmiAuthtype = ipmiAuthtype;
		this.ipmiPrivilege = ipmiPrivilege;
		this.ipmiUsername = ipmiUsername;
		this.ipmiPassword = ipmiPassword;
		this.ipmiDisableUntil = ipmiDisableUntil;
		this.ipmiAvailable = ipmiAvailable;
		this.snmpDisableUntil = snmpDisableUntil;
		this.snmpAvailable = snmpAvailable;
		this.maintenanceStatus = maintenanceStatus;
		this.maintenanceType = maintenanceType;
		this.maintenanceFrom = maintenanceFrom;
		this.ipmiErrorsFrom = ipmiErrorsFrom;
		this.snmpErrorsFrom = snmpErrorsFrom;
		this.ipmiError = ipmiError;
		this.snmpError = snmpError;
		this.jmxDisableUntil = jmxDisableUntil;
		this.jmxAvailable = jmxAvailable;
		this.jmxErrorsFrom = jmxErrorsFrom;
		this.jmxError = jmxError;
		this.name = name;
		this.maintenancesHostses = maintenancesHostses;
		this.screenses = screenses;
		this.opcommandHsts = opcommandHsts;
		this.hostsTemplatesesForHostid = hostsTemplatesesForHostid;
		this.hostsTemplatesesForTemplateid = hostsTemplatesesForTemplateid;
		this.druleses = druleses;
		this.hostmacros = hostmacros;
		this.optemplates = optemplates;
		this.hostInventory = hostInventory;
		this.applicationses = applicationses;
		this.itemses = itemses;
		this.autoregHosts = autoregHosts;
		this.interfaceses = interfaceses;
		this.hostsGroupses = hostsGroupses;
		this.hostses = hostses;
	}

	@Id
	@Column(name = "hostid", unique = true, nullable = false)
	public Long getHostid() {
		return this.hostid;
	}

	public void setHostid(Long hostid) {
		this.hostid = hostid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maintenanceid")
	public Maintenances getMaintenances() {
		return this.maintenances;
	}

	public void setMaintenances(Maintenances maintenances) {
		this.maintenances = maintenances;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proxy_hostid")
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@Column(name = "host", nullable = false, length = 64)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "status", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "disable_until", nullable = false)
	public int getDisableUntil() {
		return this.disableUntil;
	}

	public void setDisableUntil(int disableUntil) {
		this.disableUntil = disableUntil;
	}

	@Column(name = "error", nullable = false, length = 128)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "available", nullable = false)
	public int getAvailable() {
		return this.available;
	}

	public void setAvailable(int available) {
		this.available = available;
	}

	@Column(name = "errors_from", nullable = false)
	public int getErrorsFrom() {
		return this.errorsFrom;
	}

	public void setErrorsFrom(int errorsFrom) {
		this.errorsFrom = errorsFrom;
	}

	@Column(name = "lastaccess", nullable = false)
	public int getLastaccess() {
		return this.lastaccess;
	}

	public void setLastaccess(int lastaccess) {
		this.lastaccess = lastaccess;
	}

	@Column(name = "ipmi_authtype", nullable = false)
	public int getIpmiAuthtype() {
		return this.ipmiAuthtype;
	}

	public void setIpmiAuthtype(int ipmiAuthtype) {
		this.ipmiAuthtype = ipmiAuthtype;
	}

	@Column(name = "ipmi_privilege", nullable = false)
	public int getIpmiPrivilege() {
		return this.ipmiPrivilege;
	}

	public void setIpmiPrivilege(int ipmiPrivilege) {
		this.ipmiPrivilege = ipmiPrivilege;
	}

	@Column(name = "ipmi_username", nullable = false, length = 16)
	public String getIpmiUsername() {
		return this.ipmiUsername;
	}

	public void setIpmiUsername(String ipmiUsername) {
		this.ipmiUsername = ipmiUsername;
	}

	@Column(name = "ipmi_password", nullable = false, length = 20)
	public String getIpmiPassword() {
		return this.ipmiPassword;
	}

	public void setIpmiPassword(String ipmiPassword) {
		this.ipmiPassword = ipmiPassword;
	}

	@Column(name = "ipmi_disable_until", nullable = false)
	public int getIpmiDisableUntil() {
		return this.ipmiDisableUntil;
	}

	public void setIpmiDisableUntil(int ipmiDisableUntil) {
		this.ipmiDisableUntil = ipmiDisableUntil;
	}

	@Column(name = "ipmi_available", nullable = false)
	public int getIpmiAvailable() {
		return this.ipmiAvailable;
	}

	public void setIpmiAvailable(int ipmiAvailable) {
		this.ipmiAvailable = ipmiAvailable;
	}

	@Column(name = "snmp_disable_until", nullable = false)
	public int getSnmpDisableUntil() {
		return this.snmpDisableUntil;
	}

	public void setSnmpDisableUntil(int snmpDisableUntil) {
		this.snmpDisableUntil = snmpDisableUntil;
	}

	@Column(name = "snmp_available", nullable = false)
	public int getSnmpAvailable() {
		return this.snmpAvailable;
	}

	public void setSnmpAvailable(int snmpAvailable) {
		this.snmpAvailable = snmpAvailable;
	}

	@Column(name = "maintenance_status", nullable = false)
	public int getMaintenanceStatus() {
		return this.maintenanceStatus;
	}

	public void setMaintenanceStatus(int maintenanceStatus) {
		this.maintenanceStatus = maintenanceStatus;
	}

	@Column(name = "maintenance_type", nullable = false)
	public int getMaintenanceType() {
		return this.maintenanceType;
	}

	public void setMaintenanceType(int maintenanceType) {
		this.maintenanceType = maintenanceType;
	}

	@Column(name = "maintenance_from", nullable = false)
	public int getMaintenanceFrom() {
		return this.maintenanceFrom;
	}

	public void setMaintenanceFrom(int maintenanceFrom) {
		this.maintenanceFrom = maintenanceFrom;
	}

	@Column(name = "ipmi_errors_from", nullable = false)
	public int getIpmiErrorsFrom() {
		return this.ipmiErrorsFrom;
	}

	public void setIpmiErrorsFrom(int ipmiErrorsFrom) {
		this.ipmiErrorsFrom = ipmiErrorsFrom;
	}

	@Column(name = "snmp_errors_from", nullable = false)
	public int getSnmpErrorsFrom() {
		return this.snmpErrorsFrom;
	}

	public void setSnmpErrorsFrom(int snmpErrorsFrom) {
		this.snmpErrorsFrom = snmpErrorsFrom;
	}

	@Column(name = "ipmi_error", nullable = false, length = 128)
	public String getIpmiError() {
		return this.ipmiError;
	}

	public void setIpmiError(String ipmiError) {
		this.ipmiError = ipmiError;
	}

	@Column(name = "snmp_error", nullable = false, length = 128)
	public String getSnmpError() {
		return this.snmpError;
	}

	public void setSnmpError(String snmpError) {
		this.snmpError = snmpError;
	}

	@Column(name = "jmx_disable_until", nullable = false)
	public int getJmxDisableUntil() {
		return this.jmxDisableUntil;
	}

	public void setJmxDisableUntil(int jmxDisableUntil) {
		this.jmxDisableUntil = jmxDisableUntil;
	}

	@Column(name = "jmx_available", nullable = false)
	public int getJmxAvailable() {
		return this.jmxAvailable;
	}

	public void setJmxAvailable(int jmxAvailable) {
		this.jmxAvailable = jmxAvailable;
	}

	@Column(name = "jmx_errors_from", nullable = false)
	public int getJmxErrorsFrom() {
		return this.jmxErrorsFrom;
	}

	public void setJmxErrorsFrom(int jmxErrorsFrom) {
		this.jmxErrorsFrom = jmxErrorsFrom;
	}

	@Column(name = "jmx_error", nullable = false, length = 128)
	public String getJmxError() {
		return this.jmxError;
	}

	public void setJmxError(String jmxError) {
		this.jmxError = jmxError;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<MaintenancesHosts> getMaintenancesHostses() {
		return this.maintenancesHostses;
	}

	public void setMaintenancesHostses(Set<MaintenancesHosts> maintenancesHostses) {
		this.maintenancesHostses = maintenancesHostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Screens> getScreenses() {
		return this.screenses;
	}

	public void setScreenses(Set<Screens> screenses) {
		this.screenses = screenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<OpcommandHst> getOpcommandHsts() {
		return this.opcommandHsts;
	}

	public void setOpcommandHsts(Set<OpcommandHst> opcommandHsts) {
		this.opcommandHsts = opcommandHsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostsByHostid")
	public Set<HostsTemplates> getHostsTemplatesesForHostid() {
		return this.hostsTemplatesesForHostid;
	}

	public void setHostsTemplatesesForHostid(Set<HostsTemplates> hostsTemplatesesForHostid) {
		this.hostsTemplatesesForHostid = hostsTemplatesesForHostid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostsByTemplateid")
	public Set<HostsTemplates> getHostsTemplatesesForTemplateid() {
		return this.hostsTemplatesesForTemplateid;
	}

	public void setHostsTemplatesesForTemplateid(Set<HostsTemplates> hostsTemplatesesForTemplateid) {
		this.hostsTemplatesesForTemplateid = hostsTemplatesesForTemplateid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Drules> getDruleses() {
		return this.druleses;
	}

	public void setDruleses(Set<Drules> druleses) {
		this.druleses = druleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Hostmacro> getHostmacros() {
		return this.hostmacros;
	}

	public void setHostmacros(Set<Hostmacro> hostmacros) {
		this.hostmacros = hostmacros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Optemplate> getOptemplates() {
		return this.optemplates;
	}

	public void setOptemplates(Set<Optemplate> optemplates) {
		this.optemplates = optemplates;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "hosts")
	public HostInventory getHostInventory() {
		return this.hostInventory;
	}

	public void setHostInventory(HostInventory hostInventory) {
		this.hostInventory = hostInventory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Applications> getApplicationses() {
		return this.applicationses;
	}

	public void setApplicationses(Set<Applications> applicationses) {
		this.applicationses = applicationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<AutoregHost> getAutoregHosts() {
		return this.autoregHosts;
	}

	public void setAutoregHosts(Set<AutoregHost> autoregHosts) {
		this.autoregHosts = autoregHosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Interfaces> getInterfaceses() {
		return this.interfaceses;
	}

	public void setInterfaceses(Set<Interfaces> interfaceses) {
		this.interfaceses = interfaceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<HostsGroups> getHostsGroupses() {
		return this.hostsGroupses;
	}

	public void setHostsGroupses(Set<HostsGroups> hostsGroupses) {
		this.hostsGroupses = hostsGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hosts")
	public Set<Hosts> getHostses() {
		return this.hostses;
	}

	public void setHostses(Set<Hosts> hostses) {
		this.hostses = hostses;
	}

}
