package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HostsTemplates generated by hbm2java
 */
@Entity
@Table(name = "hosts_templates", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "hostid",
		"templateid" }))
public class HostsTemplates implements java.io.Serializable {

	private long hosttemplateid;
	private Hosts hostsByHostid;
	private Hosts hostsByTemplateid;

	public HostsTemplates() {
	}

	public HostsTemplates(long hosttemplateid, Hosts hostsByHostid, Hosts hostsByTemplateid) {
		this.hosttemplateid = hosttemplateid;
		this.hostsByHostid = hostsByHostid;
		this.hostsByTemplateid = hostsByTemplateid;
	}

	@Id
	@Column(name = "hosttemplateid", unique = true, nullable = false)
	public long getHosttemplateid() {
		return this.hosttemplateid;
	}

	public void setHosttemplateid(long hosttemplateid) {
		this.hosttemplateid = hosttemplateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hostid", nullable = false)
	public Hosts getHostsByHostid() {
		return this.hostsByHostid;
	}

	public void setHostsByHostid(Hosts hostsByHostid) {
		this.hostsByHostid = hostsByHostid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid", nullable = false)
	public Hosts getHostsByTemplateid() {
		return this.hostsByTemplateid;
	}

	public void setHostsByTemplateid(Hosts hostsByTemplateid) {
		this.hostsByTemplateid = hostsByTemplateid;
	}

}
