package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Hostmacro generated by hbm2java
 */
@Entity
@Table(name = "hostmacro", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "hostid",
		"macro" }))
public class Hostmacro implements java.io.Serializable {

	private long hostmacroid;
	private Hosts hosts;
	private String macro;
	private String value;

	public Hostmacro() {
	}

	public Hostmacro(long hostmacroid, Hosts hosts, String macro, String value) {
		this.hostmacroid = hostmacroid;
		this.hosts = hosts;
		this.macro = macro;
		this.value = value;
	}

	@Id
	@Column(name = "hostmacroid", unique = true, nullable = false)
	public long getHostmacroid() {
		return this.hostmacroid;
	}

	public void setHostmacroid(long hostmacroid) {
		this.hostmacroid = hostmacroid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hostid", nullable = false)
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@Column(name = "macro", nullable = false, length = 64)
	public String getMacro() {
		return this.macro;
	}

	public void setMacro(String macro) {
		this.macro = macro;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
