package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Housekeeper generated by hbm2java
 */
@Entity
@Table(name = "housekeeper", catalog = "skycloud")
public class Housekeeper implements java.io.Serializable {

	private long housekeeperid;
	private String tablename;
	private String field;
	private long value;

	public Housekeeper() {
	}

	public Housekeeper(long housekeeperid, String tablename, String field, long value) {
		this.housekeeperid = housekeeperid;
		this.tablename = tablename;
		this.field = field;
		this.value = value;
	}

	@Id
	@Column(name = "housekeeperid", unique = true, nullable = false)
	public long getHousekeeperid() {
		return this.housekeeperid;
	}

	public void setHousekeeperid(long housekeeperid) {
		this.housekeeperid = housekeeperid;
	}

	@Column(name = "tablename", nullable = false, length = 64)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "field", nullable = false, length = 64)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "value", nullable = false)
	public long getValue() {
		return this.value;
	}

	public void setValue(long value) {
		this.value = value;
	}

}
