package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Httpstepitem generated by hbm2java
 */
@Entity
@Table(name = "httpstepitem", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "httpstepid",
		"itemid" }))
public class Httpstepitem implements java.io.Serializable {

	private long httpstepitemid;
	private Httpstep httpstep;
	private Items items;
	private int type;

	public Httpstepitem() {
	}

	public Httpstepitem(long httpstepitemid, Httpstep httpstep, Items items, int type) {
		this.httpstepitemid = httpstepitemid;
		this.httpstep = httpstep;
		this.items = items;
		this.type = type;
	}

	@Id
	@Column(name = "httpstepitemid", unique = true, nullable = false)
	public long getHttpstepitemid() {
		return this.httpstepitemid;
	}

	public void setHttpstepitemid(long httpstepitemid) {
		this.httpstepitemid = httpstepitemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "httpstepid", nullable = false)
	public Httpstep getHttpstep() {
		return this.httpstep;
	}

	public void setHttpstep(Httpstep httpstep) {
		this.httpstep = httpstep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
