package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Httptestitem generated by hbm2java
 */
@Entity
@Table(name = "httptestitem", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "httptestid",
		"itemid" }))
public class Httptestitem implements java.io.Serializable {

	private long httptestitemid;
	private Httptest httptest;
	private Items items;
	private int type;

	public Httptestitem() {
	}

	public Httptestitem(long httptestitemid, Httptest httptest, Items items, int type) {
		this.httptestitemid = httptestitemid;
		this.httptest = httptest;
		this.items = items;
		this.type = type;
	}

	@Id
	@Column(name = "httptestitemid", unique = true, nullable = false)
	public long getHttptestitemid() {
		return this.httptestitemid;
	}

	public void setHttptestitemid(long httptestitemid) {
		this.httptestitemid = httptestitemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "httptestid", nullable = false)
	public Httptest getHttptest() {
		return this.httptest;
	}

	public void setHttptest(Httptest httptest) {
		this.httptest = httptest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
