package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Httpstep generated by hbm2java
 */
@Entity
@Table(name = "httpstep", catalog = "skycloud")
public class Httpstep implements java.io.Serializable {

	private long httpstepid;
	private Httptest httptest;
	private String name;
	private int no;
	private String url;
	private int timeout;
	private String posts;
	private String required;
	private String statusCodes;
	private Set<Httpstepitem> httpstepitems = new HashSet<Httpstepitem>(0);

	public Httpstep() {
	}

	public Httpstep(long httpstepid, Httptest httptest, String name, int no, String url, int timeout, String posts,
			String required, String statusCodes) {
		this.httpstepid = httpstepid;
		this.httptest = httptest;
		this.name = name;
		this.no = no;
		this.url = url;
		this.timeout = timeout;
		this.posts = posts;
		this.required = required;
		this.statusCodes = statusCodes;
	}

	public Httpstep(long httpstepid, Httptest httptest, String name, int no, String url, int timeout, String posts,
			String required, String statusCodes, Set<Httpstepitem> httpstepitems) {
		this.httpstepid = httpstepid;
		this.httptest = httptest;
		this.name = name;
		this.no = no;
		this.url = url;
		this.timeout = timeout;
		this.posts = posts;
		this.required = required;
		this.statusCodes = statusCodes;
		this.httpstepitems = httpstepitems;
	}

	@Id
	@Column(name = "httpstepid", unique = true, nullable = false)
	public long getHttpstepid() {
		return this.httpstepid;
	}

	public void setHttpstepid(long httpstepid) {
		this.httpstepid = httpstepid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "httptestid", nullable = false)
	public Httptest getHttptest() {
		return this.httptest;
	}

	public void setHttptest(Httptest httptest) {
		this.httptest = httptest;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "no", nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "timeout", nullable = false)
	public int getTimeout() {
		return this.timeout;
	}

	public void setTimeout(int timeout) {
		this.timeout = timeout;
	}

	@Column(name = "posts", nullable = false, length = 65535)
	public String getPosts() {
		return this.posts;
	}

	public void setPosts(String posts) {
		this.posts = posts;
	}

	@Column(name = "required", nullable = false)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "status_codes", nullable = false)
	public String getStatusCodes() {
		return this.statusCodes;
	}

	public void setStatusCodes(String statusCodes) {
		this.statusCodes = statusCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "httpstep")
	public Set<Httpstepitem> getHttpstepitems() {
		return this.httpstepitems;
	}

	public void setHttpstepitems(Set<Httpstepitem> httpstepitems) {
		this.httpstepitems = httpstepitems;
	}

}
