package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IconMapping generated by hbm2java
 */
@Entity
@Table(name = "icon_mapping", catalog = "skycloud")
public class IconMapping implements java.io.Serializable {

	private long iconmappingid;
	private Images images;
	private IconMap iconMap;
	private int inventoryLink;
	private String expression;
	private int sortorder;

	public IconMapping() {
	}

	public IconMapping(long iconmappingid, Images images, IconMap iconMap, int inventoryLink, String expression,
			int sortorder) {
		this.iconmappingid = iconmappingid;
		this.images = images;
		this.iconMap = iconMap;
		this.inventoryLink = inventoryLink;
		this.expression = expression;
		this.sortorder = sortorder;
	}

	@Id
	@Column(name = "iconmappingid", unique = true, nullable = false)
	public long getIconmappingid() {
		return this.iconmappingid;
	}

	public void setIconmappingid(long iconmappingid) {
		this.iconmappingid = iconmappingid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconid", nullable = false)
	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconmapid", nullable = false)
	public IconMap getIconMap() {
		return this.iconMap;
	}

	public void setIconMap(IconMap iconMap) {
		this.iconMap = iconMap;
	}

	@Column(name = "inventory_link", nullable = false)
	public int getInventoryLink() {
		return this.inventoryLink;
	}

	public void setInventoryLink(int inventoryLink) {
		this.inventoryLink = inventoryLink;
	}

	@Column(name = "expression", nullable = false, length = 64)
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "sortorder", nullable = false)
	public int getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(int sortorder) {
		this.sortorder = sortorder;
	}

}
