package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IconMap generated by hbm2java
 */
@Entity
@Table(name = "icon_map", catalog = "skycloud")
public class IconMap implements java.io.Serializable {

	private long iconmapid;
	private Images images;
	private String name;
	private Set<IconMapping> iconMappings = new HashSet<IconMapping>(0);
	private Set<Sysmaps> sysmapses = new HashSet<Sysmaps>(0);

	public IconMap() {
	}

	public IconMap(long iconmapid, Images images, String name) {
		this.iconmapid = iconmapid;
		this.images = images;
		this.name = name;
	}

	public IconMap(long iconmapid, Images images, String name, Set<IconMapping> iconMappings, Set<Sysmaps> sysmapses) {
		this.iconmapid = iconmapid;
		this.images = images;
		this.name = name;
		this.iconMappings = iconMappings;
		this.sysmapses = sysmapses;
	}

	@Id
	@Column(name = "iconmapid", unique = true, nullable = false)
	public long getIconmapid() {
		return this.iconmapid;
	}

	public void setIconmapid(long iconmapid) {
		this.iconmapid = iconmapid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "default_iconid", nullable = false)
	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iconMap")
	public Set<IconMapping> getIconMappings() {
		return this.iconMappings;
	}

	public void setIconMappings(Set<IconMapping> iconMappings) {
		this.iconMappings = iconMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iconMap")
	public Set<Sysmaps> getSysmapses() {
		return this.sysmapses;
	}

	public void setSysmapses(Set<Sysmaps> sysmapses) {
		this.sysmapses = sysmapses;
	}

}
