package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdsId generated by hbm2java
 */
@Embeddable
public class IdsId implements java.io.Serializable {

	private int nodeid;
	private String tableName;
	private String fieldName;

	public IdsId() {
	}

	public IdsId(int nodeid, String tableName, String fieldName) {
		this.nodeid = nodeid;
		this.tableName = tableName;
		this.fieldName = fieldName;
	}

	@Column(name = "nodeid", nullable = false)
	public int getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(int nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "table_name", nullable = false, length = 64)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "field_name", nullable = false, length = 64)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IdsId))
			return false;
		IdsId castOther = (IdsId) other;

		return (this.getNodeid() == castOther.getNodeid())
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this.getFieldName() != null
						&& castOther.getFieldName() != null && this.getFieldName().equals(castOther.getFieldName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNodeid();
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		return result;
	}

}
