package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemDiscovery generated by hbm2java
 */
@Entity
@Table(name = "item_discovery", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "itemid",
		"parent_itemid" }))
public class ItemDiscovery implements java.io.Serializable {

	private long itemdiscoveryid;
	private Items itemsByParentItemid;
	private Items itemsByItemid;
	private String key;
	private int lastcheck;
	private int tsDelete;

	public ItemDiscovery() {
	}

	public ItemDiscovery(long itemdiscoveryid, Items itemsByParentItemid, Items itemsByItemid, String key,
			int lastcheck, int tsDelete) {
		this.itemdiscoveryid = itemdiscoveryid;
		this.itemsByParentItemid = itemsByParentItemid;
		this.itemsByItemid = itemsByItemid;
		this.key = key;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	@Id
	@Column(name = "itemdiscoveryid", unique = true, nullable = false)
	public long getItemdiscoveryid() {
		return this.itemdiscoveryid;
	}

	public void setItemdiscoveryid(long itemdiscoveryid) {
		this.itemdiscoveryid = itemdiscoveryid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_itemid", nullable = false)
	public Items getItemsByParentItemid() {
		return this.itemsByParentItemid;
	}

	public void setItemsByParentItemid(Items itemsByParentItemid) {
		this.itemsByParentItemid = itemsByParentItemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Items getItemsByItemid() {
		return this.itemsByItemid;
	}

	public void setItemsByItemid(Items itemsByItemid) {
		this.itemsByItemid = itemsByItemid;
	}

	@Column(name = "key_", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "lastcheck", nullable = false)
	public int getLastcheck() {
		return this.lastcheck;
	}

	public void setLastcheck(int lastcheck) {
		this.lastcheck = lastcheck;
	}

	@Column(name = "ts_delete", nullable = false)
	public int getTsDelete() {
		return this.tsDelete;
	}

	public void setTsDelete(int tsDelete) {
		this.tsDelete = tsDelete;
	}

}
