package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemsApplications generated by hbm2java
 */
@Entity
@Table(name = "items_applications", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"applicationid", "itemid" }))
public class ItemsApplications implements java.io.Serializable {

	private long itemappid;
	private Applications applications;
	private Items items;

	public ItemsApplications() {
	}

	public ItemsApplications(long itemappid, Applications applications, Items items) {
		this.itemappid = itemappid;
		this.applications = applications;
		this.items = items;
	}

	@Id
	@Column(name = "itemappid", unique = true, nullable = false)
	public long getItemappid() {
		return this.itemappid;
	}

	public void setItemappid(long itemappid) {
		this.itemappid = itemappid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicationid", nullable = false)
	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

}
