package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "items", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "hostid", "key_" }))
public class Items implements java.io.Serializable {

	private long itemid;
	private Hosts hosts;
	private Items items;
	private Interfaces interfaces;
	private Valuemaps valuemaps;
	private int type;
	private String snmpCommunity;
	private String snmpOid;
	private String name;
	private String key;
	private int delay;
	private int history;
	private int trends;
	private String lastvalue;
	private Integer lastclock;
	private String prevvalue;
	private int status;
	private int valueType;
	private String trapperHosts;
	private String units;
	private int multiplier;
	private int delta;
	private String prevorgvalue;
	private String snmpv3Securityname;
	private int snmpv3Securitylevel;
	private String snmpv3Authpassphrase;
	private String snmpv3Privpassphrase;
	private String formula;
	private String error;
	private long lastlogsize;
	private String logtimefmt;
	private String delayFlex;
	private String params;
	private String ipmiSensor;
	private int dataType;
	private int authtype;
	private String username;
	private String password;
	private String publickey;
	private String privatekey;
	private int mtime;
	private Integer lastns;
	private int flags;
	private String filter;
	private String port;
	private String description;
	private int inventoryLink;
	private String lifetime;
	private Set<Httpstepitem> httpstepitems = new HashSet<Httpstepitem>(0);
	private Set<Graphs> graphsesForYmaxItemid = new HashSet<Graphs>(0);
	private Set<Graphs> graphsesForYminItemid = new HashSet<Graphs>(0);
	private Set<Functions> functionses = new HashSet<Functions>(0);
	private Set<GraphsItems> graphsItemses = new HashSet<GraphsItems>(0);
	private Set<ItemDiscovery> itemDiscoveriesForItemid = new HashSet<ItemDiscovery>(0);
	private Set<Httptestitem> httptestitems = new HashSet<Httptestitem>(0);
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<ItemDiscovery> itemDiscoveriesForParentItemid = new HashSet<ItemDiscovery>(0);
	private Set<ItemsApplications> itemsApplicationses = new HashSet<ItemsApplications>(0);

	public Items() {
	}

	public Items(long itemid, Hosts hosts, int type, String snmpCommunity, String snmpOid, String name, String key,
			int delay, int history, int trends, int status, int valueType, String trapperHosts, String units,
			int multiplier, int delta, String snmpv3Securityname, int snmpv3Securitylevel, String snmpv3Authpassphrase,
			String snmpv3Privpassphrase, String formula, String error, long lastlogsize, String logtimefmt,
			String delayFlex, String params, String ipmiSensor, int dataType, int authtype, String username,
			String password, String publickey, String privatekey, int mtime, int flags, String filter, String port,
			String description, int inventoryLink, String lifetime) {
		this.itemid = itemid;
		this.hosts = hosts;
		this.type = type;
		this.snmpCommunity = snmpCommunity;
		this.snmpOid = snmpOid;
		this.name = name;
		this.key = key;
		this.delay = delay;
		this.history = history;
		this.trends = trends;
		this.status = status;
		this.valueType = valueType;
		this.trapperHosts = trapperHosts;
		this.units = units;
		this.multiplier = multiplier;
		this.delta = delta;
		this.snmpv3Securityname = snmpv3Securityname;
		this.snmpv3Securitylevel = snmpv3Securitylevel;
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
		this.formula = formula;
		this.error = error;
		this.lastlogsize = lastlogsize;
		this.logtimefmt = logtimefmt;
		this.delayFlex = delayFlex;
		this.params = params;
		this.ipmiSensor = ipmiSensor;
		this.dataType = dataType;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.mtime = mtime;
		this.flags = flags;
		this.filter = filter;
		this.port = port;
		this.description = description;
		this.inventoryLink = inventoryLink;
		this.lifetime = lifetime;
	}

	public Items(long itemid, Hosts hosts, Items items, Interfaces interfaces, Valuemaps valuemaps, int type,
			String snmpCommunity, String snmpOid, String name, String key, int delay, int history, int trends,
			String lastvalue, Integer lastclock, String prevvalue, int status, int valueType, String trapperHosts,
			String units, int multiplier, int delta, String prevorgvalue, String snmpv3Securityname,
			int snmpv3Securitylevel, String snmpv3Authpassphrase, String snmpv3Privpassphrase, String formula,
			String error, long lastlogsize, String logtimefmt, String delayFlex, String params, String ipmiSensor,
			int dataType, int authtype, String username, String password, String publickey, String privatekey,
			int mtime, Integer lastns, int flags, String filter, String port, String description, int inventoryLink,
			String lifetime, Set<Httpstepitem> httpstepitems, Set<Graphs> graphsesForYmaxItemid,
			Set<Graphs> graphsesForYminItemid, Set<Functions> functionses, Set<GraphsItems> graphsItemses,
			Set<ItemDiscovery> itemDiscoveriesForItemid, Set<Httptestitem> httptestitems, Set<Items> itemses,
			Set<ItemDiscovery> itemDiscoveriesForParentItemid, Set<ItemsApplications> itemsApplicationses) {
		this.itemid = itemid;
		this.hosts = hosts;
		this.items = items;
		this.interfaces = interfaces;
		this.valuemaps = valuemaps;
		this.type = type;
		this.snmpCommunity = snmpCommunity;
		this.snmpOid = snmpOid;
		this.name = name;
		this.key = key;
		this.delay = delay;
		this.history = history;
		this.trends = trends;
		this.lastvalue = lastvalue;
		this.lastclock = lastclock;
		this.prevvalue = prevvalue;
		this.status = status;
		this.valueType = valueType;
		this.trapperHosts = trapperHosts;
		this.units = units;
		this.multiplier = multiplier;
		this.delta = delta;
		this.prevorgvalue = prevorgvalue;
		this.snmpv3Securityname = snmpv3Securityname;
		this.snmpv3Securitylevel = snmpv3Securitylevel;
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
		this.formula = formula;
		this.error = error;
		this.lastlogsize = lastlogsize;
		this.logtimefmt = logtimefmt;
		this.delayFlex = delayFlex;
		this.params = params;
		this.ipmiSensor = ipmiSensor;
		this.dataType = dataType;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.mtime = mtime;
		this.lastns = lastns;
		this.flags = flags;
		this.filter = filter;
		this.port = port;
		this.description = description;
		this.inventoryLink = inventoryLink;
		this.lifetime = lifetime;
		this.httpstepitems = httpstepitems;
		this.graphsesForYmaxItemid = graphsesForYmaxItemid;
		this.graphsesForYminItemid = graphsesForYminItemid;
		this.functionses = functionses;
		this.graphsItemses = graphsItemses;
		this.itemDiscoveriesForItemid = itemDiscoveriesForItemid;
		this.httptestitems = httptestitems;
		this.itemses = itemses;
		this.itemDiscoveriesForParentItemid = itemDiscoveriesForParentItemid;
		this.itemsApplicationses = itemsApplicationses;
	}

	@Id
	@Column(name = "itemid", unique = true, nullable = false)
	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hostid", nullable = false)
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interfaceid")
	public Interfaces getInterfaces() {
		return this.interfaces;
	}

	public void setInterfaces(Interfaces interfaces) {
		this.interfaces = interfaces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "valuemapid")
	public Valuemaps getValuemaps() {
		return this.valuemaps;
	}

	public void setValuemaps(Valuemaps valuemaps) {
		this.valuemaps = valuemaps;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "snmp_community", nullable = false, length = 64)
	public String getSnmpCommunity() {
		return this.snmpCommunity;
	}

	public void setSnmpCommunity(String snmpCommunity) {
		this.snmpCommunity = snmpCommunity;
	}

	@Column(name = "snmp_oid", nullable = false)
	public String getSnmpOid() {
		return this.snmpOid;
	}

	public void setSnmpOid(String snmpOid) {
		this.snmpOid = snmpOid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "key_", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "delay", nullable = false)
	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

	@Column(name = "history", nullable = false)
	public int getHistory() {
		return this.history;
	}

	public void setHistory(int history) {
		this.history = history;
	}

	@Column(name = "trends", nullable = false)
	public int getTrends() {
		return this.trends;
	}

	public void setTrends(int trends) {
		this.trends = trends;
	}

	@Column(name = "lastvalue")
	public String getLastvalue() {
		return this.lastvalue;
	}

	public void setLastvalue(String lastvalue) {
		this.lastvalue = lastvalue;
	}

	@Column(name = "lastclock")
	public Integer getLastclock() {
		return this.lastclock;
	}

	public void setLastclock(Integer lastclock) {
		this.lastclock = lastclock;
	}

	@Column(name = "prevvalue")
	public String getPrevvalue() {
		return this.prevvalue;
	}

	public void setPrevvalue(String prevvalue) {
		this.prevvalue = prevvalue;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "value_type", nullable = false)
	public int getValueType() {
		return this.valueType;
	}

	public void setValueType(int valueType) {
		this.valueType = valueType;
	}

	@Column(name = "trapper_hosts", nullable = false)
	public String getTrapperHosts() {
		return this.trapperHosts;
	}

	public void setTrapperHosts(String trapperHosts) {
		this.trapperHosts = trapperHosts;
	}

	@Column(name = "units", nullable = false)
	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	@Column(name = "multiplier", nullable = false)
	public int getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(int multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "delta", nullable = false)
	public int getDelta() {
		return this.delta;
	}

	public void setDelta(int delta) {
		this.delta = delta;
	}

	@Column(name = "prevorgvalue")
	public String getPrevorgvalue() {
		return this.prevorgvalue;
	}

	public void setPrevorgvalue(String prevorgvalue) {
		this.prevorgvalue = prevorgvalue;
	}

	@Column(name = "snmpv3_securityname", nullable = false, length = 64)
	public String getSnmpv3Securityname() {
		return this.snmpv3Securityname;
	}

	public void setSnmpv3Securityname(String snmpv3Securityname) {
		this.snmpv3Securityname = snmpv3Securityname;
	}

	@Column(name = "snmpv3_securitylevel", nullable = false)
	public int getSnmpv3Securitylevel() {
		return this.snmpv3Securitylevel;
	}

	public void setSnmpv3Securitylevel(int snmpv3Securitylevel) {
		this.snmpv3Securitylevel = snmpv3Securitylevel;
	}

	@Column(name = "snmpv3_authpassphrase", nullable = false, length = 64)
	public String getSnmpv3Authpassphrase() {
		return this.snmpv3Authpassphrase;
	}

	public void setSnmpv3Authpassphrase(String snmpv3Authpassphrase) {
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
	}

	@Column(name = "snmpv3_privpassphrase", nullable = false, length = 64)
	public String getSnmpv3Privpassphrase() {
		return this.snmpv3Privpassphrase;
	}

	public void setSnmpv3Privpassphrase(String snmpv3Privpassphrase) {
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
	}

	@Column(name = "formula", nullable = false)
	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	@Column(name = "error", nullable = false, length = 128)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "lastlogsize", nullable = false)
	public long getLastlogsize() {
		return this.lastlogsize;
	}

	public void setLastlogsize(long lastlogsize) {
		this.lastlogsize = lastlogsize;
	}

	@Column(name = "logtimefmt", nullable = false, length = 64)
	public String getLogtimefmt() {
		return this.logtimefmt;
	}

	public void setLogtimefmt(String logtimefmt) {
		this.logtimefmt = logtimefmt;
	}

	@Column(name = "delay_flex", nullable = false)
	public String getDelayFlex() {
		return this.delayFlex;
	}

	public void setDelayFlex(String delayFlex) {
		this.delayFlex = delayFlex;
	}

	@Column(name = "params", nullable = false, length = 65535)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "ipmi_sensor", nullable = false, length = 128)
	public String getIpmiSensor() {
		return this.ipmiSensor;
	}

	public void setIpmiSensor(String ipmiSensor) {
		this.ipmiSensor = ipmiSensor;
	}

	@Column(name = "data_type", nullable = false)
	public int getDataType() {
		return this.dataType;
	}

	public void setDataType(int dataType) {
		this.dataType = dataType;
	}

	@Column(name = "authtype", nullable = false)
	public int getAuthtype() {
		return this.authtype;
	}

	public void setAuthtype(int authtype) {
		this.authtype = authtype;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "publickey", nullable = false, length = 64)
	public String getPublickey() {
		return this.publickey;
	}

	public void setPublickey(String publickey) {
		this.publickey = publickey;
	}

	@Column(name = "privatekey", nullable = false, length = 64)
	public String getPrivatekey() {
		return this.privatekey;
	}

	public void setPrivatekey(String privatekey) {
		this.privatekey = privatekey;
	}

	@Column(name = "mtime", nullable = false)
	public int getMtime() {
		return this.mtime;
	}

	public void setMtime(int mtime) {
		this.mtime = mtime;
	}

	@Column(name = "lastns")
	public Integer getLastns() {
		return this.lastns;
	}

	public void setLastns(Integer lastns) {
		this.lastns = lastns;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "filter", nullable = false)
	public String getFilter() {
		return this.filter;
	}

	public void setFilter(String filter) {
		this.filter = filter;
	}

	@Column(name = "port", nullable = false, length = 64)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "inventory_link", nullable = false)
	public int getInventoryLink() {
		return this.inventoryLink;
	}

	public void setInventoryLink(int inventoryLink) {
		this.inventoryLink = inventoryLink;
	}

	@Column(name = "lifetime", nullable = false, length = 64)
	public String getLifetime() {
		return this.lifetime;
	}

	public void setLifetime(String lifetime) {
		this.lifetime = lifetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Httpstepitem> getHttpstepitems() {
		return this.httpstepitems;
	}

	public void setHttpstepitems(Set<Httpstepitem> httpstepitems) {
		this.httpstepitems = httpstepitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByYmaxItemid")
	public Set<Graphs> getGraphsesForYmaxItemid() {
		return this.graphsesForYmaxItemid;
	}

	public void setGraphsesForYmaxItemid(Set<Graphs> graphsesForYmaxItemid) {
		this.graphsesForYmaxItemid = graphsesForYmaxItemid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByYminItemid")
	public Set<Graphs> getGraphsesForYminItemid() {
		return this.graphsesForYminItemid;
	}

	public void setGraphsesForYminItemid(Set<Graphs> graphsesForYminItemid) {
		this.graphsesForYminItemid = graphsesForYminItemid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Functions> getFunctionses() {
		return this.functionses;
	}

	public void setFunctionses(Set<Functions> functionses) {
		this.functionses = functionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<GraphsItems> getGraphsItemses() {
		return this.graphsItemses;
	}

	public void setGraphsItemses(Set<GraphsItems> graphsItemses) {
		this.graphsItemses = graphsItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByItemid")
	public Set<ItemDiscovery> getItemDiscoveriesForItemid() {
		return this.itemDiscoveriesForItemid;
	}

	public void setItemDiscoveriesForItemid(Set<ItemDiscovery> itemDiscoveriesForItemid) {
		this.itemDiscoveriesForItemid = itemDiscoveriesForItemid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Httptestitem> getHttptestitems() {
		return this.httptestitems;
	}

	public void setHttptestitems(Set<Httptestitem> httptestitems) {
		this.httptestitems = httptestitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByParentItemid")
	public Set<ItemDiscovery> getItemDiscoveriesForParentItemid() {
		return this.itemDiscoveriesForParentItemid;
	}

	public void setItemDiscoveriesForParentItemid(Set<ItemDiscovery> itemDiscoveriesForParentItemid) {
		this.itemDiscoveriesForParentItemid = itemDiscoveriesForParentItemid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<ItemsApplications> getItemsApplicationses() {
		return this.itemsApplicationses;
	}

	public void setItemsApplicationses(Set<ItemsApplications> itemsApplicationses) {
		this.itemsApplicationses = itemsApplicationses;
	}

}
