package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MaintenancesWindows generated by hbm2java
 */
@Entity
@Table(name = "maintenances_windows", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"maintenanceid", "timeperiodid" }))
public class MaintenancesWindows implements java.io.Serializable {

	private long maintenanceTimeperiodid;
	private Maintenances maintenances;
	private Timeperiods timeperiods;

	public MaintenancesWindows() {
	}

	public MaintenancesWindows(long maintenanceTimeperiodid, Maintenances maintenances, Timeperiods timeperiods) {
		this.maintenanceTimeperiodid = maintenanceTimeperiodid;
		this.maintenances = maintenances;
		this.timeperiods = timeperiods;
	}

	@Id
	@Column(name = "maintenance_timeperiodid", unique = true, nullable = false)
	public long getMaintenanceTimeperiodid() {
		return this.maintenanceTimeperiodid;
	}

	public void setMaintenanceTimeperiodid(long maintenanceTimeperiodid) {
		this.maintenanceTimeperiodid = maintenanceTimeperiodid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maintenanceid", nullable = false)
	public Maintenances getMaintenances() {
		return this.maintenances;
	}

	public void setMaintenances(Maintenances maintenances) {
		this.maintenances = maintenances;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "timeperiodid", nullable = false)
	public Timeperiods getTimeperiods() {
		return this.timeperiods;
	}

	public void setTimeperiods(Timeperiods timeperiods) {
		this.timeperiods = timeperiods;
	}

}
