package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maintenances generated by hbm2java
 */
@Entity
@Table(name = "maintenances", catalog = "skycloud")
public class Maintenances implements java.io.Serializable {

	private long maintenanceid;
	private String name;
	private int maintenanceType;
	private String description;
	private int activeSince;
	private int activeTill;
	private Set<MaintenancesHosts> maintenancesHostses = new HashSet<MaintenancesHosts>(0);
	private Set<MaintenancesWindows> maintenancesWindowses = new HashSet<MaintenancesWindows>(0);
	private Set<MaintenancesGroups> maintenancesGroupses = new HashSet<MaintenancesGroups>(0);
	private Set<Hosts> hostses = new HashSet<Hosts>(0);

	public Maintenances() {
	}

	public Maintenances(long maintenanceid, String name, int maintenanceType, String description, int activeSince,
			int activeTill) {
		this.maintenanceid = maintenanceid;
		this.name = name;
		this.maintenanceType = maintenanceType;
		this.description = description;
		this.activeSince = activeSince;
		this.activeTill = activeTill;
	}

	public Maintenances(long maintenanceid, String name, int maintenanceType, String description, int activeSince,
			int activeTill, Set<MaintenancesHosts> maintenancesHostses, Set<MaintenancesWindows> maintenancesWindowses,
			Set<MaintenancesGroups> maintenancesGroupses, Set<Hosts> hostses) {
		this.maintenanceid = maintenanceid;
		this.name = name;
		this.maintenanceType = maintenanceType;
		this.description = description;
		this.activeSince = activeSince;
		this.activeTill = activeTill;
		this.maintenancesHostses = maintenancesHostses;
		this.maintenancesWindowses = maintenancesWindowses;
		this.maintenancesGroupses = maintenancesGroupses;
		this.hostses = hostses;
	}

	@Id
	@Column(name = "maintenanceid", unique = true, nullable = false)
	public long getMaintenanceid() {
		return this.maintenanceid;
	}

	public void setMaintenanceid(long maintenanceid) {
		this.maintenanceid = maintenanceid;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "maintenance_type", nullable = false)
	public int getMaintenanceType() {
		return this.maintenanceType;
	}

	public void setMaintenanceType(int maintenanceType) {
		this.maintenanceType = maintenanceType;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "active_since", nullable = false)
	public int getActiveSince() {
		return this.activeSince;
	}

	public void setActiveSince(int activeSince) {
		this.activeSince = activeSince;
	}

	@Column(name = "active_till", nullable = false)
	public int getActiveTill() {
		return this.activeTill;
	}

	public void setActiveTill(int activeTill) {
		this.activeTill = activeTill;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maintenances")
	public Set<MaintenancesHosts> getMaintenancesHostses() {
		return this.maintenancesHostses;
	}

	public void setMaintenancesHostses(Set<MaintenancesHosts> maintenancesHostses) {
		this.maintenancesHostses = maintenancesHostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maintenances")
	public Set<MaintenancesWindows> getMaintenancesWindowses() {
		return this.maintenancesWindowses;
	}

	public void setMaintenancesWindowses(Set<MaintenancesWindows> maintenancesWindowses) {
		this.maintenancesWindowses = maintenancesWindowses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maintenances")
	public Set<MaintenancesGroups> getMaintenancesGroupses() {
		return this.maintenancesGroupses;
	}

	public void setMaintenancesGroupses(Set<MaintenancesGroups> maintenancesGroupses) {
		this.maintenancesGroupses = maintenancesGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maintenances")
	public Set<Hosts> getHostses() {
		return this.hostses;
	}

	public void setHostses(Set<Hosts> hostses) {
		this.hostses = hostses;
	}

}
