package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mappings generated by hbm2java
 */
@Entity
@Table(name = "mappings", catalog = "skycloud")
public class Mappings implements java.io.Serializable {

	private long mappingid;
	private Valuemaps valuemaps;
	private String value;
	private String newvalue;

	public Mappings() {
	}

	public Mappings(long mappingid, Valuemaps valuemaps, String value, String newvalue) {
		this.mappingid = mappingid;
		this.valuemaps = valuemaps;
		this.value = value;
		this.newvalue = newvalue;
	}

	@Id
	@Column(name = "mappingid", unique = true, nullable = false)
	public long getMappingid() {
		return this.mappingid;
	}

	public void setMappingid(long mappingid) {
		this.mappingid = mappingid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "valuemapid", nullable = false)
	public Valuemaps getValuemaps() {
		return this.valuemaps;
	}

	public void setValuemaps(Valuemaps valuemaps) {
		this.valuemaps = valuemaps;
	}

	@Column(name = "value", nullable = false, length = 64)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "newvalue", nullable = false, length = 64)
	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

}
