package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MediaType generated by hbm2java
 */
@Entity
@Table(name = "media_type", catalog = "skycloud")
public class MediaType implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -1338000952504289828L;
	private long mediatypeid;
	private int type;
	private String description;
	private String smtpServer;
	private String smtpHelo;
	private String smtpEmail;
	private String execPath;
	private String gsmModem;
	private String username;
	private String passwd;
	private int status;
	private Set<Media> medias = new HashSet<Media>(0);
	private Set<Alerts> alertses = new HashSet<Alerts>(0);
	private Set<Opmessage> opmessages = new HashSet<Opmessage>(0);

	public MediaType() {
	}

	public MediaType(long mediatypeid, int type, String description, String smtpServer, String smtpHelo,
			String smtpEmail, String execPath, String gsmModem, String username, String passwd, int status) {
		this.mediatypeid = mediatypeid;
		this.type = type;
		this.description = description;
		this.smtpServer = smtpServer;
		this.smtpHelo = smtpHelo;
		this.smtpEmail = smtpEmail;
		this.execPath = execPath;
		this.gsmModem = gsmModem;
		this.username = username;
		this.passwd = passwd;
		this.status = status;
	}

	public MediaType(long mediatypeid, int type, String description, String smtpServer, String smtpHelo,
			String smtpEmail, String execPath, String gsmModem, String username, String passwd, int status,
			Set<Media> medias, Set<Alerts> alertses, Set<Opmessage> opmessages) {
		this.mediatypeid = mediatypeid;
		this.type = type;
		this.description = description;
		this.smtpServer = smtpServer;
		this.smtpHelo = smtpHelo;
		this.smtpEmail = smtpEmail;
		this.execPath = execPath;
		this.gsmModem = gsmModem;
		this.username = username;
		this.passwd = passwd;
		this.status = status;
		this.medias = medias;
		this.alertses = alertses;
		this.opmessages = opmessages;
	}

	@Id
	@Column(name = "mediatypeid", unique = true, nullable = false)
	public long getMediatypeid() {
		return this.mediatypeid;
	}

	public void setMediatypeid(long mediatypeid) {
		this.mediatypeid = mediatypeid;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "smtp_server", nullable = false)
	public String getSmtpServer() {
		return this.smtpServer;
	}

	public void setSmtpServer(String smtpServer) {
		this.smtpServer = smtpServer;
	}

	@Column(name = "smtp_helo", nullable = false)
	public String getSmtpHelo() {
		return this.smtpHelo;
	}

	public void setSmtpHelo(String smtpHelo) {
		this.smtpHelo = smtpHelo;
	}

	@Column(name = "smtp_email", nullable = false)
	public String getSmtpEmail() {
		return this.smtpEmail;
	}

	public void setSmtpEmail(String smtpEmail) {
		this.smtpEmail = smtpEmail;
	}

	@Column(name = "exec_path", nullable = false)
	public String getExecPath() {
		return this.execPath;
	}

	public void setExecPath(String execPath) {
		this.execPath = execPath;
	}

	@Column(name = "gsm_modem", nullable = false)
	public String getGsmModem() {
		return this.gsmModem;
	}

	public void setGsmModem(String gsmModem) {
		this.gsmModem = gsmModem;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "passwd", nullable = false)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaType")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaType")
	public Set<Alerts> getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set<Alerts> alertses) {
		this.alertses = alertses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaType")
	public Set<Opmessage> getOpmessages() {
		return this.opmessages;
	}

	public void setOpmessages(Set<Opmessage> opmessages) {
		this.opmessages = opmessages;
	}

}
