package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nodes generated by hbm2java
 */
@Entity
@Table(name = "nodes", catalog = "skycloud")
public class Nodes implements java.io.Serializable {

	private int nodeid;
	private Nodes nodes;
	private String name;
	private String ip;
	private int port;
	private int nodetype;
	private Set<Nodes> nodeses = new HashSet<Nodes>(0);
	private Set<NodeCksum> nodeCksums = new HashSet<NodeCksum>(0);

	public Nodes() {
	}

	public Nodes(int nodeid, String name, String ip, int port, int nodetype) {
		this.nodeid = nodeid;
		this.name = name;
		this.ip = ip;
		this.port = port;
		this.nodetype = nodetype;
	}

	public Nodes(int nodeid, Nodes nodes, String name, String ip, int port, int nodetype, Set<Nodes> nodeses,
			Set<NodeCksum> nodeCksums) {
		this.nodeid = nodeid;
		this.nodes = nodes;
		this.name = name;
		this.ip = ip;
		this.port = port;
		this.nodetype = nodetype;
		this.nodeses = nodeses;
		this.nodeCksums = nodeCksums;
	}

	@Id
	@Column(name = "nodeid", unique = true, nullable = false)
	public int getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(int nodeid) {
		this.nodeid = nodeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "masterid")
	public Nodes getNodes() {
		return this.nodes;
	}

	public void setNodes(Nodes nodes) {
		this.nodes = nodes;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ip", nullable = false, length = 39)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "nodetype", nullable = false)
	public int getNodetype() {
		return this.nodetype;
	}

	public void setNodetype(int nodetype) {
		this.nodetype = nodetype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodes")
	public Set<Nodes> getNodeses() {
		return this.nodeses;
	}

	public void setNodeses(Set<Nodes> nodeses) {
		this.nodeses = nodeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodes")
	public Set<NodeCksum> getNodeCksums() {
		return this.nodeCksums;
	}

	public void setNodeCksums(Set<NodeCksum> nodeCksums) {
		this.nodeCksums = nodeCksums;
	}

}
