package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NodeCksumId generated by hbm2java
 */
@Embeddable
public class NodeCksumId implements java.io.Serializable {

	private int nodeid;
	private String tablename;
	private long recordid;
	private int cksumtype;
	private String cksum;
	private String sync;

	public NodeCksumId() {
	}

	public NodeCksumId(int nodeid, String tablename, long recordid, int cksumtype, String cksum, String sync) {
		this.nodeid = nodeid;
		this.tablename = tablename;
		this.recordid = recordid;
		this.cksumtype = cksumtype;
		this.cksum = cksum;
		this.sync = sync;
	}

	@Column(name = "nodeid", nullable = false)
	public int getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(int nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "tablename", nullable = false, length = 64)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "recordid", nullable = false)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "cksumtype", nullable = false)
	public int getCksumtype() {
		return this.cksumtype;
	}

	public void setCksumtype(int cksumtype) {
		this.cksumtype = cksumtype;
	}

	@Column(name = "cksum", nullable = false, length = 65535)
	public String getCksum() {
		return this.cksum;
	}

	public void setCksum(String cksum) {
		this.cksum = cksum;
	}

	@Column(name = "sync", nullable = false, length = 128)
	public String getSync() {
		return this.sync;
	}

	public void setSync(String sync) {
		this.sync = sync;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NodeCksumId))
			return false;
		NodeCksumId castOther = (NodeCksumId) other;

		return (this.getNodeid() == castOther.getNodeid())
				&& ((this.getTablename() == castOther.getTablename()) || (this.getTablename() != null
						&& castOther.getTablename() != null && this.getTablename().equals(castOther.getTablename())))
				&& (this.getRecordid() == castOther.getRecordid())
				&& (this.getCksumtype() == castOther.getCksumtype())
				&& ((this.getCksum() == castOther.getCksum()) || (this.getCksum() != null
						&& castOther.getCksum() != null && this.getCksum().equals(castOther.getCksum())))
				&& ((this.getSync() == castOther.getSync()) || (this.getSync() != null && castOther.getSync() != null && this
						.getSync().equals(castOther.getSync())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNodeid();
		result = 37 * result + (getTablename() == null ? 0 : this.getTablename().hashCode());
		result = 37 * result + (int) this.getRecordid();
		result = 37 * result + this.getCksumtype();
		result = 37 * result + (getCksum() == null ? 0 : this.getCksum().hashCode());
		result = 37 * result + (getSync() == null ? 0 : this.getSync().hashCode());
		return result;
	}

}
