package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Opcommand generated by hbm2java
 */
@Entity
@Table(name = "opcommand", catalog = "skycloud")
public class Opcommand implements java.io.Serializable {

	private long operationid;
	private Scripts scripts;
	private Operations operations;
	private int type;
	private int executeOn;
	private String port;
	private int authtype;
	private String username;
	private String password;
	private String publickey;
	private String privatekey;
	private String command;

	public Opcommand() {
	}

	public Opcommand(Operations operations, int type, int executeOn, String port, int authtype, String username,
			String password, String publickey, String privatekey, String command) {
		this.operations = operations;
		this.type = type;
		this.executeOn = executeOn;
		this.port = port;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.command = command;
	}

	public Opcommand(Scripts scripts, Operations operations, int type, int executeOn, String port, int authtype,
			String username, String password, String publickey, String privatekey, String command) {
		this.scripts = scripts;
		this.operations = operations;
		this.type = type;
		this.executeOn = executeOn;
		this.port = port;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.command = command;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "operations"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "operationid", unique = true, nullable = false)
	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scriptid")
	public Scripts getScripts() {
		return this.scripts;
	}

	public void setScripts(Scripts scripts) {
		this.scripts = scripts;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "execute_on", nullable = false)
	public int getExecuteOn() {
		return this.executeOn;
	}

	public void setExecuteOn(int executeOn) {
		this.executeOn = executeOn;
	}

	@Column(name = "port", nullable = false, length = 64)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "authtype", nullable = false)
	public int getAuthtype() {
		return this.authtype;
	}

	public void setAuthtype(int authtype) {
		this.authtype = authtype;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "publickey", nullable = false, length = 64)
	public String getPublickey() {
		return this.publickey;
	}

	public void setPublickey(String publickey) {
		this.publickey = publickey;
	}

	@Column(name = "privatekey", nullable = false, length = 64)
	public String getPrivatekey() {
		return this.privatekey;
	}

	public void setPrivatekey(String privatekey) {
		this.privatekey = privatekey;
	}

	@Column(name = "command", nullable = false, length = 65535)
	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

}
