package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OpcommandGrp generated by hbm2java
 */
@Entity
@Table(name = "opcommand_grp", catalog = "skycloud")
public class OpcommandGrp implements java.io.Serializable {

	private long opcommandGrpid;
	private Groups groups;
	private Operations operations;

	public OpcommandGrp() {
	}

	public OpcommandGrp(long opcommandGrpid, Groups groups, Operations operations) {
		this.opcommandGrpid = opcommandGrpid;
		this.groups = groups;
		this.operations = operations;
	}

	@Id
	@Column(name = "opcommand_grpid", unique = true, nullable = false)
	public long getOpcommandGrpid() {
		return this.opcommandGrpid;
	}

	public void setOpcommandGrpid(long opcommandGrpid) {
		this.opcommandGrpid = opcommandGrpid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid", nullable = false)
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationid", nullable = false)
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

}
