package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Opconditions generated by hbm2java
 */
@Entity
@Table(name = "opconditions", catalog = "skycloud")
public class Opconditions implements java.io.Serializable {

	private long opconditionid;
	private Operations operations;
	private int conditiontype;
	private int operator;
	private String value;

	public Opconditions() {
	}

	public Opconditions(long opconditionid, Operations operations, int conditiontype, int operator, String value) {
		this.opconditionid = opconditionid;
		this.operations = operations;
		this.conditiontype = conditiontype;
		this.operator = operator;
		this.value = value;
	}

	@Id
	@Column(name = "opconditionid", unique = true, nullable = false)
	public long getOpconditionid() {
		return this.opconditionid;
	}

	public void setOpconditionid(long opconditionid) {
		this.opconditionid = opconditionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationid", nullable = false)
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	@Column(name = "conditiontype", nullable = false)
	public int getConditiontype() {
		return this.conditiontype;
	}

	public void setConditiontype(int conditiontype) {
		this.conditiontype = conditiontype;
	}

	@Column(name = "operator", nullable = false)
	public int getOperator() {
		return this.operator;
	}

	public void setOperator(int operator) {
		this.operator = operator;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
