package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OpcommandHst generated by hbm2java
 */
@Entity
@Table(name = "opcommand_hst", catalog = "skycloud")
public class OpcommandHst implements java.io.Serializable {

	private long opcommandHstid;
	private Hosts hosts;
	private Operations operations;

	public OpcommandHst() {
	}

	public OpcommandHst(long opcommandHstid, Operations operations) {
		this.opcommandHstid = opcommandHstid;
		this.operations = operations;
	}

	public OpcommandHst(long opcommandHstid, Hosts hosts, Operations operations) {
		this.opcommandHstid = opcommandHstid;
		this.hosts = hosts;
		this.operations = operations;
	}

	@Id
	@Column(name = "opcommand_hstid", unique = true, nullable = false)
	public long getOpcommandHstid() {
		return this.opcommandHstid;
	}

	public void setOpcommandHstid(long opcommandHstid) {
		this.opcommandHstid = opcommandHstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hostid")
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationid", nullable = false)
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

}
