package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Operations generated by hbm2java
 */
@Entity
@Table(name = "operations", catalog = "skycloud")
public class Operations implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = 8252620854506969282L;
	private long operationid;
	private Actions actions;
	private int operationtype;
	private int escPeriod;
	private int escStepFrom;
	private int escStepTo;
	private int evaltype;
	private Set<OpcommandHst> opcommandHsts = new HashSet<OpcommandHst>(0);
	private Set<Optemplate> optemplates = new HashSet<Optemplate>(0);
	private Set<OpmessageUsr> opmessageUsrs = new HashSet<OpmessageUsr>(0);
	private Set<OpcommandGrp> opcommandGrps = new HashSet<OpcommandGrp>(0);
	private Set<Opconditions> opconditionses = new HashSet<Opconditions>(0);
	private Opcommand opcommand;
	private Set<Opgroup> opgroups = new HashSet<Opgroup>(0);
	private Set<OpmessageGrp> opmessageGrps = new HashSet<OpmessageGrp>(0);
	private Opmessage opmessage;

	public Operations() {
	}

	public Operations(long operationid, Actions actions, int operationtype, int escPeriod, int escStepFrom,
			int escStepTo, int evaltype) {
		this.operationid = operationid;
		this.actions = actions;
		this.operationtype = operationtype;
		this.escPeriod = escPeriod;
		this.escStepFrom = escStepFrom;
		this.escStepTo = escStepTo;
		this.evaltype = evaltype;
	}

	public Operations(long operationid, Actions actions, int operationtype, int escPeriod, int escStepFrom,
			int escStepTo, int evaltype, Set<OpcommandHst> opcommandHsts, Set<Optemplate> optemplates,
			Set<OpmessageUsr> opmessageUsrs, Set<OpcommandGrp> opcommandGrps, Set<Opconditions> opconditionses,
			Opcommand opcommand, Set<Opgroup> opgroups, Set<OpmessageGrp> opmessageGrps, Opmessage opmessage) {
		this.operationid = operationid;
		this.actions = actions;
		this.operationtype = operationtype;
		this.escPeriod = escPeriod;
		this.escStepFrom = escStepFrom;
		this.escStepTo = escStepTo;
		this.evaltype = evaltype;
		this.opcommandHsts = opcommandHsts;
		this.optemplates = optemplates;
		this.opmessageUsrs = opmessageUsrs;
		this.opcommandGrps = opcommandGrps;
		this.opconditionses = opconditionses;
		this.opcommand = opcommand;
		this.opgroups = opgroups;
		this.opmessageGrps = opmessageGrps;
		this.opmessage = opmessage;
	}

	@Id
	@Column(name = "operationid", unique = true, nullable = false)
	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actionid", nullable = false)
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@Column(name = "operationtype", nullable = false)
	public int getOperationtype() {
		return this.operationtype;
	}

	public void setOperationtype(int operationtype) {
		this.operationtype = operationtype;
	}

	@Column(name = "esc_period", nullable = false)
	public int getEscPeriod() {
		return this.escPeriod;
	}

	public void setEscPeriod(int escPeriod) {
		this.escPeriod = escPeriod;
	}

	@Column(name = "esc_step_from", nullable = false)
	public int getEscStepFrom() {
		return this.escStepFrom;
	}

	public void setEscStepFrom(int escStepFrom) {
		this.escStepFrom = escStepFrom;
	}

	@Column(name = "esc_step_to", nullable = false)
	public int getEscStepTo() {
		return this.escStepTo;
	}

	public void setEscStepTo(int escStepTo) {
		this.escStepTo = escStepTo;
	}

	@Column(name = "evaltype", nullable = false)
	public int getEvaltype() {
		return this.evaltype;
	}

	public void setEvaltype(int evaltype) {
		this.evaltype = evaltype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<OpcommandHst> getOpcommandHsts() {
		return this.opcommandHsts;
	}

	public void setOpcommandHsts(Set<OpcommandHst> opcommandHsts) {
		this.opcommandHsts = opcommandHsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<Optemplate> getOptemplates() {
		return this.optemplates;
	}

	public void setOptemplates(Set<Optemplate> optemplates) {
		this.optemplates = optemplates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<OpmessageUsr> getOpmessageUsrs() {
		return this.opmessageUsrs;
	}

	public void setOpmessageUsrs(Set<OpmessageUsr> opmessageUsrs) {
		this.opmessageUsrs = opmessageUsrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<OpcommandGrp> getOpcommandGrps() {
		return this.opcommandGrps;
	}

	public void setOpcommandGrps(Set<OpcommandGrp> opcommandGrps) {
		this.opcommandGrps = opcommandGrps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<Opconditions> getOpconditionses() {
		return this.opconditionses;
	}

	public void setOpconditionses(Set<Opconditions> opconditionses) {
		this.opconditionses = opconditionses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "operations")
	public Opcommand getOpcommand() {
		return this.opcommand;
	}

	public void setOpcommand(Opcommand opcommand) {
		this.opcommand = opcommand;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<Opgroup> getOpgroups() {
		return this.opgroups;
	}

	public void setOpgroups(Set<Opgroup> opgroups) {
		this.opgroups = opgroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<OpmessageGrp> getOpmessageGrps() {
		return this.opmessageGrps;
	}

	public void setOpmessageGrps(Set<OpmessageGrp> opmessageGrps) {
		this.opmessageGrps = opmessageGrps;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "operations")
	public Opmessage getOpmessage() {
		return this.opmessage;
	}

	public void setOpmessage(Opmessage opmessage) {
		this.opmessage = opmessage;
	}

}
