package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Opgroup generated by hbm2java
 */
@Entity
@Table(name = "opgroup", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "operationid",
		"groupid" }))
public class Opgroup implements java.io.Serializable {

	private long opgroupid;
	private Groups groups;
	private Operations operations;

	public Opgroup() {
	}

	public Opgroup(long opgroupid, Groups groups, Operations operations) {
		this.opgroupid = opgroupid;
		this.groups = groups;
		this.operations = operations;
	}

	@Id
	@Column(name = "opgroupid", unique = true, nullable = false)
	public long getOpgroupid() {
		return this.opgroupid;
	}

	public void setOpgroupid(long opgroupid) {
		this.opgroupid = opgroupid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid", nullable = false)
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationid", nullable = false)
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

}
