package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Opmessage generated by hbm2java
 */
@Entity
@Table(name = "opmessage", catalog = "skycloud")
public class Opmessage implements java.io.Serializable {

	private long operationid;
	private Operations operations;
	private MediaType mediaType;
	private int defaultMsg;
	private String subject;
	private String message;

	public Opmessage() {
	}

	public Opmessage(Operations operations, int defaultMsg, String subject, String message) {
		this.operations = operations;
		this.defaultMsg = defaultMsg;
		this.subject = subject;
		this.message = message;
	}

	public Opmessage(Operations operations, MediaType mediaType, int defaultMsg, String subject, String message) {
		this.operations = operations;
		this.mediaType = mediaType;
		this.defaultMsg = defaultMsg;
		this.subject = subject;
		this.message = message;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "operations"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "operationid", unique = true, nullable = false)
	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mediatypeid")
	public MediaType getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(MediaType mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "default_msg", nullable = false)
	public int getDefaultMsg() {
		return this.defaultMsg;
	}

	public void setDefaultMsg(int defaultMsg) {
		this.defaultMsg = defaultMsg;
	}

	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
