package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Optemplate generated by hbm2java
 */
@Entity
@Table(name = "optemplate", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "operationid",
		"templateid" }))
public class Optemplate implements java.io.Serializable {

	private long optemplateid;
	private Operations operations;
	private Hosts hosts;

	public Optemplate() {
	}

	public Optemplate(long optemplateid, Operations operations, Hosts hosts) {
		this.optemplateid = optemplateid;
		this.operations = operations;
		this.hosts = hosts;
	}

	@Id
	@Column(name = "optemplateid", unique = true, nullable = false)
	public long getOptemplateid() {
		return this.optemplateid;
	}

	public void setOptemplateid(long optemplateid) {
		this.optemplateid = optemplateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationid", nullable = false)
	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid", nullable = false)
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

}
