package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Profiles generated by hbm2java
 */
@Entity
@Table(name = "profiles", catalog = "skycloud")
public class Profiles implements java.io.Serializable {

	private long profileid;
	private Users users;
	private String idx;
	private long idx2;
	private long valueId;
	private int valueInt;
	private String valueStr;
	private String source;
	private int type;

	public Profiles() {
	}

	public Profiles(long profileid, Users users, String idx, long idx2, long valueId, int valueInt, String valueStr,
			String source, int type) {
		this.profileid = profileid;
		this.users = users;
		this.idx = idx;
		this.idx2 = idx2;
		this.valueId = valueId;
		this.valueInt = valueInt;
		this.valueStr = valueStr;
		this.source = source;
		this.type = type;
	}

	@Id
	@Column(name = "profileid", unique = true, nullable = false)
	public long getProfileid() {
		return this.profileid;
	}

	public void setProfileid(long profileid) {
		this.profileid = profileid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "idx", nullable = false, length = 96)
	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	@Column(name = "idx2", nullable = false)
	public long getIdx2() {
		return this.idx2;
	}

	public void setIdx2(long idx2) {
		this.idx2 = idx2;
	}

	@Column(name = "value_id", nullable = false)
	public long getValueId() {
		return this.valueId;
	}

	public void setValueId(long valueId) {
		this.valueId = valueId;
	}

	@Column(name = "value_int", nullable = false)
	public int getValueInt() {
		return this.valueInt;
	}

	public void setValueInt(int valueInt) {
		this.valueInt = valueInt;
	}

	@Column(name = "value_str", nullable = false)
	public String getValueStr() {
		return this.valueStr;
	}

	public void setValueStr(String valueStr) {
		this.valueStr = valueStr;
	}

	@Column(name = "source", nullable = false, length = 96)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
