package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProxyDhistory generated by hbm2java
 */
@Entity
@Table(name = "proxy_dhistory", catalog = "skycloud")
public class ProxyDhistory implements java.io.Serializable {

	private Long id;
	private int clock;
	private long druleid;
	private int type;
	private String ip;
	private int port;
	private String key;
	private String value;
	private int status;
	private Long dcheckid;
	private String dns;

	public ProxyDhistory() {
	}

	public ProxyDhistory(int clock, long druleid, int type, String ip, int port, String key, String value, int status,
			String dns) {
		this.clock = clock;
		this.druleid = druleid;
		this.type = type;
		this.ip = ip;
		this.port = port;
		this.key = key;
		this.value = value;
		this.status = status;
		this.dns = dns;
	}

	public ProxyDhistory(int clock, long druleid, int type, String ip, int port, String key, String value, int status,
			Long dcheckid, String dns) {
		this.clock = clock;
		this.druleid = druleid;
		this.type = type;
		this.ip = ip;
		this.port = port;
		this.key = key;
		this.value = value;
		this.status = status;
		this.dcheckid = dcheckid;
		this.dns = dns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "druleid", nullable = false)
	public long getDruleid() {
		return this.druleid;
	}

	public void setDruleid(long druleid) {
		this.druleid = druleid;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "ip", nullable = false, length = 39)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "key_", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "dcheckid")
	public Long getDcheckid() {
		return this.dcheckid;
	}

	public void setDcheckid(Long dcheckid) {
		this.dcheckid = dcheckid;
	}

	@Column(name = "dns", nullable = false, length = 64)
	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

}
