package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ProxyHistory generated by hbm2java
 */
@Entity
@Table(name = "proxy_history", catalog = "skycloud")
public class ProxyHistory implements java.io.Serializable {

	private Long id;
	private int timestamp;
	private long itemid;
	private int clock;
	private String source;
	private int severity;
	private String value;
	private int logeventid;
	private int ns;
	private int status;

	public ProxyHistory() {
	}

	public ProxyHistory(long itemid, int clock, String source, int severity, String value, int logeventid, int ns,
			int status) {
		this.itemid = itemid;
		this.clock = clock;
		this.source = source;
		this.severity = severity;
		this.value = value;
		this.logeventid = logeventid;
		this.ns = ns;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "timestamp", nullable = false)
	public int getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "itemid", nullable = false)
	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "source", nullable = false, length = 64)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "severity", nullable = false)
	public int getSeverity() {
		return this.severity;
	}

	public void setSeverity(int severity) {
		this.severity = severity;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "logeventid", nullable = false)
	public int getLogeventid() {
		return this.logeventid;
	}

	public void setLogeventid(int logeventid) {
		this.logeventid = logeventid;
	}

	@Column(name = "ns", nullable = false)
	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
