package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Screens generated by hbm2java
 */
@Entity
@Table(name = "screens", catalog = "skycloud")
public class Screens implements java.io.Serializable {

	private long screenid;
	private Hosts hosts;
	private String name;
	private int hsize;
	private int vsize;
	private Set<Slides> slideses = new HashSet<Slides>(0);
	private Set<ScreensItems> screensItemses = new HashSet<ScreensItems>(0);

	public Screens() {
	}

	public Screens(long screenid, String name, int hsize, int vsize) {
		this.screenid = screenid;
		this.name = name;
		this.hsize = hsize;
		this.vsize = vsize;
	}

	public Screens(long screenid, Hosts hosts, String name, int hsize, int vsize, Set<Slides> slideses,
			Set<ScreensItems> screensItemses) {
		this.screenid = screenid;
		this.hosts = hosts;
		this.name = name;
		this.hsize = hsize;
		this.vsize = vsize;
		this.slideses = slideses;
		this.screensItemses = screensItemses;
	}

	@Id
	@Column(name = "screenid", unique = true, nullable = false)
	public long getScreenid() {
		return this.screenid;
	}

	public void setScreenid(long screenid) {
		this.screenid = screenid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateid")
	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hsize", nullable = false)
	public int getHsize() {
		return this.hsize;
	}

	public void setHsize(int hsize) {
		this.hsize = hsize;
	}

	@Column(name = "vsize", nullable = false)
	public int getVsize() {
		return this.vsize;
	}

	public void setVsize(int vsize) {
		this.vsize = vsize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screens")
	public Set<Slides> getSlideses() {
		return this.slideses;
	}

	public void setSlideses(Set<Slides> slideses) {
		this.slideses = slideses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screens")
	public Set<ScreensItems> getScreensItemses() {
		return this.screensItemses;
	}

	public void setScreensItemses(Set<ScreensItems> screensItemses) {
		this.screensItemses = screensItemses;
	}

}
