package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Scripts generated by hbm2java
 */
@Entity
@Table(name = "scripts", catalog = "skycloud")
public class Scripts implements java.io.Serializable {

	private long scriptid;
	private Groups groups;
	private Usrgrp usrgrp;
	private String name;
	private String command;
	private int hostAccess;
	private String description;
	private String confirmation;
	private int type;
	private int executeOn;
	private Set<Opcommand> opcommands = new HashSet<Opcommand>(0);

	public Scripts() {
	}

	public Scripts(long scriptid, String name, String command, int hostAccess, String description, String confirmation,
			int type, int executeOn) {
		this.scriptid = scriptid;
		this.name = name;
		this.command = command;
		this.hostAccess = hostAccess;
		this.description = description;
		this.confirmation = confirmation;
		this.type = type;
		this.executeOn = executeOn;
	}

	public Scripts(long scriptid, Groups groups, Usrgrp usrgrp, String name, String command, int hostAccess,
			String description, String confirmation, int type, int executeOn, Set<Opcommand> opcommands) {
		this.scriptid = scriptid;
		this.groups = groups;
		this.usrgrp = usrgrp;
		this.name = name;
		this.command = command;
		this.hostAccess = hostAccess;
		this.description = description;
		this.confirmation = confirmation;
		this.type = type;
		this.executeOn = executeOn;
		this.opcommands = opcommands;
	}

	@Id
	@Column(name = "scriptid", unique = true, nullable = false)
	public long getScriptid() {
		return this.scriptid;
	}

	public void setScriptid(long scriptid) {
		this.scriptid = scriptid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid")
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usrgrpid")
	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "command", nullable = false)
	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	@Column(name = "host_access", nullable = false)
	public int getHostAccess() {
		return this.hostAccess;
	}

	public void setHostAccess(int hostAccess) {
		this.hostAccess = hostAccess;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "confirmation", nullable = false)
	public String getConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(String confirmation) {
		this.confirmation = confirmation;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "execute_on", nullable = false)
	public int getExecuteOn() {
		return this.executeOn;
	}

	public void setExecuteOn(int executeOn) {
		this.executeOn = executeOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scripts")
	public Set<Opcommand> getOpcommands() {
		return this.opcommands;
	}

	public void setOpcommands(Set<Opcommand> opcommands) {
		this.opcommands = opcommands;
	}

}
