package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceAlarms generated by hbm2java
 */
@Entity
@Table(name = "service_alarms", catalog = "skycloud")
public class ServiceAlarms implements java.io.Serializable {

	private long servicealarmid;
	private Services services;
	private int clock;
	private int value;

	public ServiceAlarms() {
	}

	public ServiceAlarms(long servicealarmid, Services services, int clock, int value) {
		this.servicealarmid = servicealarmid;
		this.services = services;
		this.clock = clock;
		this.value = value;
	}

	@Id
	@Column(name = "servicealarmid", unique = true, nullable = false)
	public long getServicealarmid() {
		return this.servicealarmid;
	}

	public void setServicealarmid(long servicealarmid) {
		this.servicealarmid = servicealarmid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Column(name = "clock", nullable = false)
	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

}
