package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ServicesLinks generated by hbm2java
 */
@Entity
@Table(name = "services_links", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"serviceupid", "servicedownid" }))
public class ServicesLinks implements java.io.Serializable {

	private long linkid;
	private Services servicesByServicedownid;
	private Services servicesByServiceupid;
	private int soft;

	public ServicesLinks() {
	}

	public ServicesLinks(long linkid, Services servicesByServicedownid, Services servicesByServiceupid, int soft) {
		this.linkid = linkid;
		this.servicesByServicedownid = servicesByServicedownid;
		this.servicesByServiceupid = servicesByServiceupid;
		this.soft = soft;
	}

	@Id
	@Column(name = "linkid", unique = true, nullable = false)
	public long getLinkid() {
		return this.linkid;
	}

	public void setLinkid(long linkid) {
		this.linkid = linkid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servicedownid", nullable = false)
	public Services getServicesByServicedownid() {
		return this.servicesByServicedownid;
	}

	public void setServicesByServicedownid(Services servicesByServicedownid) {
		this.servicesByServicedownid = servicesByServicedownid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceupid", nullable = false)
	public Services getServicesByServiceupid() {
		return this.servicesByServiceupid;
	}

	public void setServicesByServiceupid(Services servicesByServiceupid) {
		this.servicesByServiceupid = servicesByServiceupid;
	}

	@Column(name = "soft", nullable = false)
	public int getSoft() {
		return this.soft;
	}

	public void setSoft(int soft) {
		this.soft = soft;
	}

}
