package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicesTimes generated by hbm2java
 */
@Entity
@Table(name = "services_times", catalog = "skycloud")
public class ServicesTimes implements java.io.Serializable {

	private long timeid;
	private Services services;
	private int type;
	private int tsFrom;
	private int tsTo;
	private String note;

	public ServicesTimes() {
	}

	public ServicesTimes(long timeid, Services services, int type, int tsFrom, int tsTo, String note) {
		this.timeid = timeid;
		this.services = services;
		this.type = type;
		this.tsFrom = tsFrom;
		this.tsTo = tsTo;
		this.note = note;
	}

	@Id
	@Column(name = "timeid", unique = true, nullable = false)
	public long getTimeid() {
		return this.timeid;
	}

	public void setTimeid(long timeid) {
		this.timeid = timeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "ts_from", nullable = false)
	public int getTsFrom() {
		return this.tsFrom;
	}

	public void setTsFrom(int tsFrom) {
		this.tsFrom = tsFrom;
	}

	@Column(name = "ts_to", nullable = false)
	public int getTsTo() {
		return this.tsTo;
	}

	public void setTsTo(int tsTo) {
		this.tsTo = tsTo;
	}

	@Column(name = "note", nullable = false)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
