package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name = "sessions", catalog = "skycloud")
public class Sessions implements java.io.Serializable {

	private String sessionid;
	private Users users;
	private int lastaccess;
	private int status;

	public Sessions() {
	}

	public Sessions(String sessionid, Users users, int lastaccess, int status) {
		this.sessionid = sessionid;
		this.users = users;
		this.lastaccess = lastaccess;
		this.status = status;
	}

	@Id
	@Column(name = "sessionid", unique = true, nullable = false, length = 32)
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "lastaccess", nullable = false)
	public int getLastaccess() {
		return this.lastaccess;
	}

	public void setLastaccess(int lastaccess) {
		this.lastaccess = lastaccess;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
