package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 10:46:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SkycloudUserinfo generated by hbm2java
 */
@Entity
@Table(name = "skycloud_userinfo", catalog = "skycloud")
public class SkycloudUserinfo implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -5413055386668858059L;
	private Integer id;
	private long userid;
	private Long departmentid;
	private String session;
	private Integer status;
	private String device;
	private Long creater;

	public SkycloudUserinfo() {
	}

	public SkycloudUserinfo(long userid) {
		this.userid = userid;
	}

	public SkycloudUserinfo(long userid, Long departmentid, String session, Integer status, String device, Long creater) {
		this.userid = userid;
		this.departmentid = departmentid;
		this.session = session;
		this.status = status;
		this.device = device;
		this.creater = creater;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", nullable = false)
	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	@Column(name = "departmentid")
	public Long getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Long departmentid) {
		this.departmentid = departmentid;
	}

	@Column(name = "session")
	public String getSession() {
		return this.session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "device")
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	@Column(name = "creater")
	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

}
