package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 10:46:46 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * SkycloudGroupstypeHost generated by hbm2java
 */
@Entity
@Table(name = "skycloud_groupstype_host", catalog = "skycloud")
public class SkycloudGroupstypeHost implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -7603227679173754969L;
	private Long TGid;
	private long typeid;
	private long hostid;
	private String assetid;
	private Long userid;
	private String mark;

	public SkycloudGroupstypeHost() {
	}

	public SkycloudGroupstypeHost(long typeid, long hostid) {
		this.typeid = typeid;
		this.hostid = hostid;
	}

	public SkycloudGroupstypeHost(long typeid, long hostid, String assetid, Long userid, String mark) {
		this.typeid = typeid;
		this.hostid = hostid;
		this.assetid = assetid;
		this.userid = userid;
		this.mark = mark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "t_gid", unique = true, nullable = false)
	public Long getTGid() {
		return this.TGid;
	}

	public void setTGid(Long TGid) {
		this.TGid = TGid;
	}

	@Column(name = "typeid", nullable = false)
	public long getTypeid() {
		return this.typeid;
	}

	public void setTypeid(long typeid) {
		this.typeid = typeid;
	}

	@Column(name = "hostid", nullable = false)
	public long getHostid() {
		return this.hostid;
	}

	public void setHostid(long hostid) {
		this.hostid = hostid;
	}

	@Column(name = "assetid", length = 36)
	@Type(type = "character")
	public String getAssetid() {
		return this.assetid;
	}

	public void setAssetid(String assetid) {
		this.assetid = assetid;
	}

	@Column(name = "userid")
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "mark", length = 100)
	@Type(type = "character")
	public String getMark() {
		return this.mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

}
