package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Slides generated by hbm2java
 */
@Entity
@Table(name = "slides", catalog = "skycloud")
public class Slides implements java.io.Serializable {

	private long slideid;
	private Screens screens;
	private Slideshows slideshows;
	private int step;
	private int delay;

	public Slides() {
	}

	public Slides(long slideid, Screens screens, Slideshows slideshows, int step, int delay) {
		this.slideid = slideid;
		this.screens = screens;
		this.slideshows = slideshows;
		this.step = step;
		this.delay = delay;
	}

	@Id
	@Column(name = "slideid", unique = true, nullable = false)
	public long getSlideid() {
		return this.slideid;
	}

	public void setSlideid(long slideid) {
		this.slideid = slideid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screenid", nullable = false)
	public Screens getScreens() {
		return this.screens;
	}

	public void setScreens(Screens screens) {
		this.screens = screens;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slideshowid", nullable = false)
	public Slideshows getSlideshows() {
		return this.slideshows;
	}

	public void setSlideshows(Slideshows slideshows) {
		this.slideshows = slideshows;
	}

	@Column(name = "step", nullable = false)
	public int getStep() {
		return this.step;
	}

	public void setStep(int step) {
		this.step = step;
	}

	@Column(name = "delay", nullable = false)
	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

}
