package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysmapsElements generated by hbm2java
 */
@Entity
@Table(name = "sysmaps_elements", catalog = "skycloud")
public class SysmapsElements implements java.io.Serializable {

	private long selementid;
	private Images imagesByIconidDisabled;
	private Images imagesByIconidOff;
	private Images imagesByIconidMaintenance;
	private Images imagesByIconidOn;
	private Sysmaps sysmaps;
	private long elementid;
	private int elementtype;
	private String label;
	private Integer labelLocation;
	private int x;
	private int y;
	private int elementsubtype;
	private int areatype;
	private int width;
	private int height;
	private int viewtype;
	private int useIconmap;
	private Set<SysmapsLinks> sysmapsLinksesForSelementid1 = new HashSet<SysmapsLinks>(0);
	private Set<SysmapsLinks> sysmapsLinksesForSelementid2 = new HashSet<SysmapsLinks>(0);
	private Set<SysmapElementUrl> sysmapElementUrls = new HashSet<SysmapElementUrl>(0);

	public SysmapsElements() {
	}

	public SysmapsElements(long selementid, Sysmaps sysmaps, long elementid, int elementtype, String label, int x,
			int y, int elementsubtype, int areatype, int width, int height, int viewtype, int useIconmap) {
		this.selementid = selementid;
		this.sysmaps = sysmaps;
		this.elementid = elementid;
		this.elementtype = elementtype;
		this.label = label;
		this.x = x;
		this.y = y;
		this.elementsubtype = elementsubtype;
		this.areatype = areatype;
		this.width = width;
		this.height = height;
		this.viewtype = viewtype;
		this.useIconmap = useIconmap;
	}

	public SysmapsElements(long selementid, Images imagesByIconidDisabled, Images imagesByIconidOff,
			Images imagesByIconidMaintenance, Images imagesByIconidOn, Sysmaps sysmaps, long elementid,
			int elementtype, String label, Integer labelLocation, int x, int y, int elementsubtype, int areatype,
			int width, int height, int viewtype, int useIconmap, Set<SysmapsLinks> sysmapsLinksesForSelementid1,
			Set<SysmapsLinks> sysmapsLinksesForSelementid2, Set<SysmapElementUrl> sysmapElementUrls) {
		this.selementid = selementid;
		this.imagesByIconidDisabled = imagesByIconidDisabled;
		this.imagesByIconidOff = imagesByIconidOff;
		this.imagesByIconidMaintenance = imagesByIconidMaintenance;
		this.imagesByIconidOn = imagesByIconidOn;
		this.sysmaps = sysmaps;
		this.elementid = elementid;
		this.elementtype = elementtype;
		this.label = label;
		this.labelLocation = labelLocation;
		this.x = x;
		this.y = y;
		this.elementsubtype = elementsubtype;
		this.areatype = areatype;
		this.width = width;
		this.height = height;
		this.viewtype = viewtype;
		this.useIconmap = useIconmap;
		this.sysmapsLinksesForSelementid1 = sysmapsLinksesForSelementid1;
		this.sysmapsLinksesForSelementid2 = sysmapsLinksesForSelementid2;
		this.sysmapElementUrls = sysmapElementUrls;
	}

	@Id
	@Column(name = "selementid", unique = true, nullable = false)
	public long getSelementid() {
		return this.selementid;
	}

	public void setSelementid(long selementid) {
		this.selementid = selementid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconid_disabled")
	public Images getImagesByIconidDisabled() {
		return this.imagesByIconidDisabled;
	}

	public void setImagesByIconidDisabled(Images imagesByIconidDisabled) {
		this.imagesByIconidDisabled = imagesByIconidDisabled;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconid_off")
	public Images getImagesByIconidOff() {
		return this.imagesByIconidOff;
	}

	public void setImagesByIconidOff(Images imagesByIconidOff) {
		this.imagesByIconidOff = imagesByIconidOff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconid_maintenance")
	public Images getImagesByIconidMaintenance() {
		return this.imagesByIconidMaintenance;
	}

	public void setImagesByIconidMaintenance(Images imagesByIconidMaintenance) {
		this.imagesByIconidMaintenance = imagesByIconidMaintenance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconid_on")
	public Images getImagesByIconidOn() {
		return this.imagesByIconidOn;
	}

	public void setImagesByIconidOn(Images imagesByIconidOn) {
		this.imagesByIconidOn = imagesByIconidOn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sysmapid", nullable = false)
	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	@Column(name = "elementid", nullable = false)
	public long getElementid() {
		return this.elementid;
	}

	public void setElementid(long elementid) {
		this.elementid = elementid;
	}

	@Column(name = "elementtype", nullable = false)
	public int getElementtype() {
		return this.elementtype;
	}

	public void setElementtype(int elementtype) {
		this.elementtype = elementtype;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "label_location")
	public Integer getLabelLocation() {
		return this.labelLocation;
	}

	public void setLabelLocation(Integer labelLocation) {
		this.labelLocation = labelLocation;
	}

	@Column(name = "x", nullable = false)
	public int getX() {
		return this.x;
	}

	public void setX(int x) {
		this.x = x;
	}

	@Column(name = "y", nullable = false)
	public int getY() {
		return this.y;
	}

	public void setY(int y) {
		this.y = y;
	}

	@Column(name = "elementsubtype", nullable = false)
	public int getElementsubtype() {
		return this.elementsubtype;
	}

	public void setElementsubtype(int elementsubtype) {
		this.elementsubtype = elementsubtype;
	}

	@Column(name = "areatype", nullable = false)
	public int getAreatype() {
		return this.areatype;
	}

	public void setAreatype(int areatype) {
		this.areatype = areatype;
	}

	@Column(name = "width", nullable = false)
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "viewtype", nullable = false)
	public int getViewtype() {
		return this.viewtype;
	}

	public void setViewtype(int viewtype) {
		this.viewtype = viewtype;
	}

	@Column(name = "use_iconmap", nullable = false)
	public int getUseIconmap() {
		return this.useIconmap;
	}

	public void setUseIconmap(int useIconmap) {
		this.useIconmap = useIconmap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmapsElementsBySelementid1")
	public Set<SysmapsLinks> getSysmapsLinksesForSelementid1() {
		return this.sysmapsLinksesForSelementid1;
	}

	public void setSysmapsLinksesForSelementid1(Set<SysmapsLinks> sysmapsLinksesForSelementid1) {
		this.sysmapsLinksesForSelementid1 = sysmapsLinksesForSelementid1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmapsElementsBySelementid2")
	public Set<SysmapsLinks> getSysmapsLinksesForSelementid2() {
		return this.sysmapsLinksesForSelementid2;
	}

	public void setSysmapsLinksesForSelementid2(Set<SysmapsLinks> sysmapsLinksesForSelementid2) {
		this.sysmapsLinksesForSelementid2 = sysmapsLinksesForSelementid2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmapsElements")
	public Set<SysmapElementUrl> getSysmapElementUrls() {
		return this.sysmapElementUrls;
	}

	public void setSysmapElementUrls(Set<SysmapElementUrl> sysmapElementUrls) {
		this.sysmapElementUrls = sysmapElementUrls;
	}

}
