package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysmapElementUrl generated by hbm2java
 */
@Entity
@Table(name = "sysmap_element_url", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"selementid", "name" }))
public class SysmapElementUrl implements java.io.Serializable {

	private long sysmapelementurlid;
	private SysmapsElements sysmapsElements;
	private String name;
	private String url;

	public SysmapElementUrl() {
	}

	public SysmapElementUrl(long sysmapelementurlid, SysmapsElements sysmapsElements, String name, String url) {
		this.sysmapelementurlid = sysmapelementurlid;
		this.sysmapsElements = sysmapsElements;
		this.name = name;
		this.url = url;
	}

	@Id
	@Column(name = "sysmapelementurlid", unique = true, nullable = false)
	public long getSysmapelementurlid() {
		return this.sysmapelementurlid;
	}

	public void setSysmapelementurlid(long sysmapelementurlid) {
		this.sysmapelementurlid = sysmapelementurlid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selementid", nullable = false)
	public SysmapsElements getSysmapsElements() {
		return this.sysmapsElements;
	}

	public void setSysmapsElements(SysmapsElements sysmapsElements) {
		this.sysmapsElements = sysmapsElements;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
