package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysmapsLinks generated by hbm2java
 */
@Entity
@Table(name = "sysmaps_links", catalog = "skycloud")
public class SysmapsLinks implements java.io.Serializable {

	private long linkid;
	private SysmapsElements sysmapsElementsBySelementid1;
	private SysmapsElements sysmapsElementsBySelementid2;
	private Sysmaps sysmaps;
	private int drawtype;
	private String color;
	private String label;
	private Set<SysmapsLinkTriggers> sysmapsLinkTriggerses = new HashSet<SysmapsLinkTriggers>(0);

	public SysmapsLinks() {
	}

	public SysmapsLinks(long linkid, SysmapsElements sysmapsElementsBySelementid1,
			SysmapsElements sysmapsElementsBySelementid2, Sysmaps sysmaps, int drawtype, String color, String label) {
		this.linkid = linkid;
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
		this.sysmaps = sysmaps;
		this.drawtype = drawtype;
		this.color = color;
		this.label = label;
	}

	public SysmapsLinks(long linkid, SysmapsElements sysmapsElementsBySelementid1,
			SysmapsElements sysmapsElementsBySelementid2, Sysmaps sysmaps, int drawtype, String color, String label,
			Set<SysmapsLinkTriggers> sysmapsLinkTriggerses) {
		this.linkid = linkid;
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
		this.sysmaps = sysmaps;
		this.drawtype = drawtype;
		this.color = color;
		this.label = label;
		this.sysmapsLinkTriggerses = sysmapsLinkTriggerses;
	}

	@Id
	@Column(name = "linkid", unique = true, nullable = false)
	public long getLinkid() {
		return this.linkid;
	}

	public void setLinkid(long linkid) {
		this.linkid = linkid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selementid1", nullable = false)
	public SysmapsElements getSysmapsElementsBySelementid1() {
		return this.sysmapsElementsBySelementid1;
	}

	public void setSysmapsElementsBySelementid1(SysmapsElements sysmapsElementsBySelementid1) {
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selementid2", nullable = false)
	public SysmapsElements getSysmapsElementsBySelementid2() {
		return this.sysmapsElementsBySelementid2;
	}

	public void setSysmapsElementsBySelementid2(SysmapsElements sysmapsElementsBySelementid2) {
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sysmapid", nullable = false)
	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	@Column(name = "drawtype", nullable = false)
	public int getDrawtype() {
		return this.drawtype;
	}

	public void setDrawtype(int drawtype) {
		this.drawtype = drawtype;
	}

	@Column(name = "color", nullable = false, length = 6)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmapsLinks")
	public Set<SysmapsLinkTriggers> getSysmapsLinkTriggerses() {
		return this.sysmapsLinkTriggerses;
	}

	public void setSysmapsLinkTriggerses(Set<SysmapsLinkTriggers> sysmapsLinkTriggerses) {
		this.sysmapsLinkTriggerses = sysmapsLinkTriggerses;
	}

}
