package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysmapUrl generated by hbm2java
 */
@Entity
@Table(name = "sysmap_url", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "sysmapid",
		"name" }))
public class SysmapUrl implements java.io.Serializable {

	private long sysmapurlid;
	private Sysmaps sysmaps;
	private String name;
	private String url;
	private int elementtype;

	public SysmapUrl() {
	}

	public SysmapUrl(long sysmapurlid, Sysmaps sysmaps, String name, String url, int elementtype) {
		this.sysmapurlid = sysmapurlid;
		this.sysmaps = sysmaps;
		this.name = name;
		this.url = url;
		this.elementtype = elementtype;
	}

	@Id
	@Column(name = "sysmapurlid", unique = true, nullable = false)
	public long getSysmapurlid() {
		return this.sysmapurlid;
	}

	public void setSysmapurlid(long sysmapurlid) {
		this.sysmapurlid = sysmapurlid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sysmapid", nullable = false)
	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "elementtype", nullable = false)
	public int getElementtype() {
		return this.elementtype;
	}

	public void setElementtype(int elementtype) {
		this.elementtype = elementtype;
	}

}
