package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sysmaps generated by hbm2java
 */
@Entity
@Table(name = "sysmaps", catalog = "skycloud")
public class Sysmaps implements java.io.Serializable {

	private long sysmapid;
	private Images images;
	private IconMap iconMap;
	private String name;
	private int width;
	private int height;
	private int labelType;
	private int labelLocation;
	private int highlight;
	private int expandproblem;
	private int markelements;
	private int showUnack;
	private int gridSize;
	private int gridShow;
	private int gridAlign;
	private int labelFormat;
	private int labelTypeHost;
	private int labelTypeHostgroup;
	private int labelTypeTrigger;
	private int labelTypeMap;
	private int labelTypeImage;
	private String labelStringHost;
	private String labelStringHostgroup;
	private String labelStringTrigger;
	private String labelStringMap;
	private String labelStringImage;
	private int expandMacros;
	private Set<SysmapsLinks> sysmapsLinkses = new HashSet<SysmapsLinks>(0);
	private Set<SysmapsElements> sysmapsElementses = new HashSet<SysmapsElements>(0);
	private Set<SysmapUrl> sysmapUrls = new HashSet<SysmapUrl>(0);

	public Sysmaps() {
	}

	public Sysmaps(long sysmapid, String name, int width, int height, int labelType, int labelLocation, int highlight,
			int expandproblem, int markelements, int showUnack, int gridSize, int gridShow, int gridAlign,
			int labelFormat, int labelTypeHost, int labelTypeHostgroup, int labelTypeTrigger, int labelTypeMap,
			int labelTypeImage, String labelStringHost, String labelStringHostgroup, String labelStringTrigger,
			String labelStringMap, String labelStringImage, int expandMacros) {
		this.sysmapid = sysmapid;
		this.name = name;
		this.width = width;
		this.height = height;
		this.labelType = labelType;
		this.labelLocation = labelLocation;
		this.highlight = highlight;
		this.expandproblem = expandproblem;
		this.markelements = markelements;
		this.showUnack = showUnack;
		this.gridSize = gridSize;
		this.gridShow = gridShow;
		this.gridAlign = gridAlign;
		this.labelFormat = labelFormat;
		this.labelTypeHost = labelTypeHost;
		this.labelTypeHostgroup = labelTypeHostgroup;
		this.labelTypeTrigger = labelTypeTrigger;
		this.labelTypeMap = labelTypeMap;
		this.labelTypeImage = labelTypeImage;
		this.labelStringHost = labelStringHost;
		this.labelStringHostgroup = labelStringHostgroup;
		this.labelStringTrigger = labelStringTrigger;
		this.labelStringMap = labelStringMap;
		this.labelStringImage = labelStringImage;
		this.expandMacros = expandMacros;
	}

	public Sysmaps(long sysmapid, Images images, IconMap iconMap, String name, int width, int height, int labelType,
			int labelLocation, int highlight, int expandproblem, int markelements, int showUnack, int gridSize,
			int gridShow, int gridAlign, int labelFormat, int labelTypeHost, int labelTypeHostgroup,
			int labelTypeTrigger, int labelTypeMap, int labelTypeImage, String labelStringHost,
			String labelStringHostgroup, String labelStringTrigger, String labelStringMap, String labelStringImage,
			int expandMacros, Set<SysmapsLinks> sysmapsLinkses, Set<SysmapsElements> sysmapsElementses,
			Set<SysmapUrl> sysmapUrls) {
		this.sysmapid = sysmapid;
		this.images = images;
		this.iconMap = iconMap;
		this.name = name;
		this.width = width;
		this.height = height;
		this.labelType = labelType;
		this.labelLocation = labelLocation;
		this.highlight = highlight;
		this.expandproblem = expandproblem;
		this.markelements = markelements;
		this.showUnack = showUnack;
		this.gridSize = gridSize;
		this.gridShow = gridShow;
		this.gridAlign = gridAlign;
		this.labelFormat = labelFormat;
		this.labelTypeHost = labelTypeHost;
		this.labelTypeHostgroup = labelTypeHostgroup;
		this.labelTypeTrigger = labelTypeTrigger;
		this.labelTypeMap = labelTypeMap;
		this.labelTypeImage = labelTypeImage;
		this.labelStringHost = labelStringHost;
		this.labelStringHostgroup = labelStringHostgroup;
		this.labelStringTrigger = labelStringTrigger;
		this.labelStringMap = labelStringMap;
		this.labelStringImage = labelStringImage;
		this.expandMacros = expandMacros;
		this.sysmapsLinkses = sysmapsLinkses;
		this.sysmapsElementses = sysmapsElementses;
		this.sysmapUrls = sysmapUrls;
	}

	@Id
	@Column(name = "sysmapid", unique = true, nullable = false)
	public long getSysmapid() {
		return this.sysmapid;
	}

	public void setSysmapid(long sysmapid) {
		this.sysmapid = sysmapid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "backgroundid")
	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iconmapid")
	public IconMap getIconMap() {
		return this.iconMap;
	}

	public void setIconMap(IconMap iconMap) {
		this.iconMap = iconMap;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "width", nullable = false)
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "label_type", nullable = false)
	public int getLabelType() {
		return this.labelType;
	}

	public void setLabelType(int labelType) {
		this.labelType = labelType;
	}

	@Column(name = "label_location", nullable = false)
	public int getLabelLocation() {
		return this.labelLocation;
	}

	public void setLabelLocation(int labelLocation) {
		this.labelLocation = labelLocation;
	}

	@Column(name = "highlight", nullable = false)
	public int getHighlight() {
		return this.highlight;
	}

	public void setHighlight(int highlight) {
		this.highlight = highlight;
	}

	@Column(name = "expandproblem", nullable = false)
	public int getExpandproblem() {
		return this.expandproblem;
	}

	public void setExpandproblem(int expandproblem) {
		this.expandproblem = expandproblem;
	}

	@Column(name = "markelements", nullable = false)
	public int getMarkelements() {
		return this.markelements;
	}

	public void setMarkelements(int markelements) {
		this.markelements = markelements;
	}

	@Column(name = "show_unack", nullable = false)
	public int getShowUnack() {
		return this.showUnack;
	}

	public void setShowUnack(int showUnack) {
		this.showUnack = showUnack;
	}

	@Column(name = "grid_size", nullable = false)
	public int getGridSize() {
		return this.gridSize;
	}

	public void setGridSize(int gridSize) {
		this.gridSize = gridSize;
	}

	@Column(name = "grid_show", nullable = false)
	public int getGridShow() {
		return this.gridShow;
	}

	public void setGridShow(int gridShow) {
		this.gridShow = gridShow;
	}

	@Column(name = "grid_align", nullable = false)
	public int getGridAlign() {
		return this.gridAlign;
	}

	public void setGridAlign(int gridAlign) {
		this.gridAlign = gridAlign;
	}

	@Column(name = "label_format", nullable = false)
	public int getLabelFormat() {
		return this.labelFormat;
	}

	public void setLabelFormat(int labelFormat) {
		this.labelFormat = labelFormat;
	}

	@Column(name = "label_type_host", nullable = false)
	public int getLabelTypeHost() {
		return this.labelTypeHost;
	}

	public void setLabelTypeHost(int labelTypeHost) {
		this.labelTypeHost = labelTypeHost;
	}

	@Column(name = "label_type_hostgroup", nullable = false)
	public int getLabelTypeHostgroup() {
		return this.labelTypeHostgroup;
	}

	public void setLabelTypeHostgroup(int labelTypeHostgroup) {
		this.labelTypeHostgroup = labelTypeHostgroup;
	}

	@Column(name = "label_type_trigger", nullable = false)
	public int getLabelTypeTrigger() {
		return this.labelTypeTrigger;
	}

	public void setLabelTypeTrigger(int labelTypeTrigger) {
		this.labelTypeTrigger = labelTypeTrigger;
	}

	@Column(name = "label_type_map", nullable = false)
	public int getLabelTypeMap() {
		return this.labelTypeMap;
	}

	public void setLabelTypeMap(int labelTypeMap) {
		this.labelTypeMap = labelTypeMap;
	}

	@Column(name = "label_type_image", nullable = false)
	public int getLabelTypeImage() {
		return this.labelTypeImage;
	}

	public void setLabelTypeImage(int labelTypeImage) {
		this.labelTypeImage = labelTypeImage;
	}

	@Column(name = "label_string_host", nullable = false)
	public String getLabelStringHost() {
		return this.labelStringHost;
	}

	public void setLabelStringHost(String labelStringHost) {
		this.labelStringHost = labelStringHost;
	}

	@Column(name = "label_string_hostgroup", nullable = false)
	public String getLabelStringHostgroup() {
		return this.labelStringHostgroup;
	}

	public void setLabelStringHostgroup(String labelStringHostgroup) {
		this.labelStringHostgroup = labelStringHostgroup;
	}

	@Column(name = "label_string_trigger", nullable = false)
	public String getLabelStringTrigger() {
		return this.labelStringTrigger;
	}

	public void setLabelStringTrigger(String labelStringTrigger) {
		this.labelStringTrigger = labelStringTrigger;
	}

	@Column(name = "label_string_map", nullable = false)
	public String getLabelStringMap() {
		return this.labelStringMap;
	}

	public void setLabelStringMap(String labelStringMap) {
		this.labelStringMap = labelStringMap;
	}

	@Column(name = "label_string_image", nullable = false)
	public String getLabelStringImage() {
		return this.labelStringImage;
	}

	public void setLabelStringImage(String labelStringImage) {
		this.labelStringImage = labelStringImage;
	}

	@Column(name = "expand_macros", nullable = false)
	public int getExpandMacros() {
		return this.expandMacros;
	}

	public void setExpandMacros(int expandMacros) {
		this.expandMacros = expandMacros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmaps")
	public Set<SysmapsLinks> getSysmapsLinkses() {
		return this.sysmapsLinkses;
	}

	public void setSysmapsLinkses(Set<SysmapsLinks> sysmapsLinkses) {
		this.sysmapsLinkses = sysmapsLinkses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmaps")
	public Set<SysmapsElements> getSysmapsElementses() {
		return this.sysmapsElementses;
	}

	public void setSysmapsElementses(Set<SysmapsElements> sysmapsElementses) {
		this.sysmapsElementses = sysmapsElementses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmaps")
	public Set<SysmapUrl> getSysmapUrls() {
		return this.sysmapUrls;
	}

	public void setSysmapUrls(Set<SysmapUrl> sysmapUrls) {
		this.sysmapUrls = sysmapUrls;
	}

}
