package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Timeperiods generated by hbm2java
 */
@Entity
@Table(name = "timeperiods", catalog = "skycloud")
public class Timeperiods implements java.io.Serializable {

	private long timeperiodid;
	private int timeperiodType;
	private int every;
	private int month;
	private int dayofweek;
	private int day;
	private int startTime;
	private int period;
	private int startDate;
	private Set<MaintenancesWindows> maintenancesWindowses = new HashSet<MaintenancesWindows>(0);

	public Timeperiods() {
	}

	public Timeperiods(long timeperiodid, int timeperiodType, int every, int month, int dayofweek, int day,
			int startTime, int period, int startDate) {
		this.timeperiodid = timeperiodid;
		this.timeperiodType = timeperiodType;
		this.every = every;
		this.month = month;
		this.dayofweek = dayofweek;
		this.day = day;
		this.startTime = startTime;
		this.period = period;
		this.startDate = startDate;
	}

	public Timeperiods(long timeperiodid, int timeperiodType, int every, int month, int dayofweek, int day,
			int startTime, int period, int startDate, Set<MaintenancesWindows> maintenancesWindowses) {
		this.timeperiodid = timeperiodid;
		this.timeperiodType = timeperiodType;
		this.every = every;
		this.month = month;
		this.dayofweek = dayofweek;
		this.day = day;
		this.startTime = startTime;
		this.period = period;
		this.startDate = startDate;
		this.maintenancesWindowses = maintenancesWindowses;
	}

	@Id
	@Column(name = "timeperiodid", unique = true, nullable = false)
	public long getTimeperiodid() {
		return this.timeperiodid;
	}

	public void setTimeperiodid(long timeperiodid) {
		this.timeperiodid = timeperiodid;
	}

	@Column(name = "timeperiod_type", nullable = false)
	public int getTimeperiodType() {
		return this.timeperiodType;
	}

	public void setTimeperiodType(int timeperiodType) {
		this.timeperiodType = timeperiodType;
	}

	@Column(name = "every", nullable = false)
	public int getEvery() {
		return this.every;
	}

	public void setEvery(int every) {
		this.every = every;
	}

	@Column(name = "month", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	@Column(name = "dayofweek", nullable = false)
	public int getDayofweek() {
		return this.dayofweek;
	}

	public void setDayofweek(int dayofweek) {
		this.dayofweek = dayofweek;
	}

	@Column(name = "day", nullable = false)
	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	@Column(name = "start_time", nullable = false)
	public int getStartTime() {
		return this.startTime;
	}

	public void setStartTime(int startTime) {
		this.startTime = startTime;
	}

	@Column(name = "period", nullable = false)
	public int getPeriod() {
		return this.period;
	}

	public void setPeriod(int period) {
		this.period = period;
	}

	@Column(name = "start_date", nullable = false)
	public int getStartDate() {
		return this.startDate;
	}

	public void setStartDate(int startDate) {
		this.startDate = startDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeperiods")
	public Set<MaintenancesWindows> getMaintenancesWindowses() {
		return this.maintenancesWindowses;
	}

	public void setMaintenancesWindowses(Set<MaintenancesWindows> maintenancesWindowses) {
		this.maintenancesWindowses = maintenancesWindowses;
	}

}
