package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Trends generated by hbm2java
 */
@Entity
@Table(name = "trends", catalog = "skycloud")
public class Trends implements java.io.Serializable {

	private TrendsId id;
	private int num;
	private double valueMin;
	private double valueAvg;
	private double valueMax;

	public Trends() {
	}

	public Trends(TrendsId id, int num, double valueMin, double valueAvg, double valueMax) {
		this.id = id;
		this.num = num;
		this.valueMin = valueMin;
		this.valueAvg = valueAvg;
		this.valueMax = valueMax;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "itemid", column = @Column(name = "itemid", nullable = false)),
			@AttributeOverride(name = "clock", column = @Column(name = "clock", nullable = false)) })
	public TrendsId getId() {
		return this.id;
	}

	public void setId(TrendsId id) {
		this.id = id;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "value_min", nullable = false, precision = 16, scale = 4)
	public double getValueMin() {
		return this.valueMin;
	}

	public void setValueMin(double valueMin) {
		this.valueMin = valueMin;
	}

	@Column(name = "value_avg", nullable = false, precision = 16, scale = 4)
	public double getValueAvg() {
		return this.valueAvg;
	}

	public void setValueAvg(double valueAvg) {
		this.valueAvg = valueAvg;
	}

	@Column(name = "value_max", nullable = false, precision = 16, scale = 4)
	public double getValueMax() {
		return this.valueMax;
	}

	public void setValueMax(double valueMax) {
		this.valueMax = valueMax;
	}

}
