package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TrendsUint generated by hbm2java
 */
@Entity
@Table(name = "trends_uint", catalog = "skycloud")
public class TrendsUint implements java.io.Serializable {

	private TrendsUintId id;
	private int num;
	private long valueMin;
	private long valueAvg;
	private long valueMax;

	public TrendsUint() {
	}

	public TrendsUint(TrendsUintId id, int num, long valueMin, long valueAvg, long valueMax) {
		this.id = id;
		this.num = num;
		this.valueMin = valueMin;
		this.valueAvg = valueAvg;
		this.valueMax = valueMax;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "itemid", column = @Column(name = "itemid", nullable = false)),
			@AttributeOverride(name = "clock", column = @Column(name = "clock", nullable = false)) })
	public TrendsUintId getId() {
		return this.id;
	}

	public void setId(TrendsUintId id) {
		this.id = id;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "value_min", nullable = false)
	public long getValueMin() {
		return this.valueMin;
	}

	public void setValueMin(long valueMin) {
		this.valueMin = valueMin;
	}

	@Column(name = "value_avg", nullable = false)
	public long getValueAvg() {
		return this.valueAvg;
	}

	public void setValueAvg(long valueAvg) {
		this.valueAvg = valueAvg;
	}

	@Column(name = "value_max", nullable = false)
	public long getValueMax() {
		return this.valueMax;
	}

	public void setValueMax(long valueMax) {
		this.valueMax = valueMax;
	}

}
