package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TriggerDepends generated by hbm2java
 */
@Entity
@Table(name = "trigger_depends", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"triggerid_down", "triggerid_up" }))
public class TriggerDepends implements java.io.Serializable {

	private long triggerdepid;
	private Triggers triggersByTriggeridDown;
	private Triggers triggersByTriggeridUp;

	public TriggerDepends() {
	}

	public TriggerDepends(long triggerdepid, Triggers triggersByTriggeridDown, Triggers triggersByTriggeridUp) {
		this.triggerdepid = triggerdepid;
		this.triggersByTriggeridDown = triggersByTriggeridDown;
		this.triggersByTriggeridUp = triggersByTriggeridUp;
	}

	@Id
	@Column(name = "triggerdepid", unique = true, nullable = false)
	public long getTriggerdepid() {
		return this.triggerdepid;
	}

	public void setTriggerdepid(long triggerdepid) {
		this.triggerdepid = triggerdepid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "triggerid_down", nullable = false)
	public Triggers getTriggersByTriggeridDown() {
		return this.triggersByTriggeridDown;
	}

	public void setTriggersByTriggeridDown(Triggers triggersByTriggeridDown) {
		this.triggersByTriggeridDown = triggersByTriggeridDown;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "triggerid_up", nullable = false)
	public Triggers getTriggersByTriggeridUp() {
		return this.triggersByTriggeridUp;
	}

	public void setTriggersByTriggeridUp(Triggers triggersByTriggeridUp) {
		this.triggersByTriggeridUp = triggersByTriggeridUp;
	}

}
