package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TriggerDiscovery generated by hbm2java
 */
@Entity
@Table(name = "trigger_discovery", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = {
		"triggerid", "parent_triggerid" }))
public class TriggerDiscovery implements java.io.Serializable {

	private long triggerdiscoveryid;
	private Triggers triggersByTriggerid;
	private Triggers triggersByParentTriggerid;
	private String name;

	public TriggerDiscovery() {
	}

	public TriggerDiscovery(long triggerdiscoveryid, Triggers triggersByTriggerid, Triggers triggersByParentTriggerid,
			String name) {
		this.triggerdiscoveryid = triggerdiscoveryid;
		this.triggersByTriggerid = triggersByTriggerid;
		this.triggersByParentTriggerid = triggersByParentTriggerid;
		this.name = name;
	}

	@Id
	@Column(name = "triggerdiscoveryid", unique = true, nullable = false)
	public long getTriggerdiscoveryid() {
		return this.triggerdiscoveryid;
	}

	public void setTriggerdiscoveryid(long triggerdiscoveryid) {
		this.triggerdiscoveryid = triggerdiscoveryid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "triggerid", nullable = false)
	public Triggers getTriggersByTriggerid() {
		return this.triggersByTriggerid;
	}

	public void setTriggersByTriggerid(Triggers triggersByTriggerid) {
		this.triggersByTriggerid = triggersByTriggerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_triggerid", nullable = false)
	public Triggers getTriggersByParentTriggerid() {
		return this.triggersByParentTriggerid;
	}

	public void setTriggersByParentTriggerid(Triggers triggersByParentTriggerid) {
		this.triggersByParentTriggerid = triggersByParentTriggerid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
