package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "skycloud")
public class Users implements java.io.Serializable {

	/** serialVersionUID [long] */
	private static final long serialVersionUID = -6910014599104234635L;
	private long userid;
	private String alias;
	private String name;
	private String surname;
	private String passwd;
	private String url;
	private int autologin;
	private int autologout;
	private String lang;
	private int refresh;
	private int type;
	private String theme;
	private int attemptFailed;
	private String attemptIp;
	private int attemptClock;
	private int rowsPerPage;
	private Set<Profiles> profileses = new HashSet<Profiles>(0);
	private Set<Auditlog> auditlogs = new HashSet<Auditlog>(0);
	private Set<Sessions> sessionses = new HashSet<Sessions>(0);
	private Set<Media> medias = new HashSet<Media>(0);
	private Set<OpmessageUsr> opmessageUsrs = new HashSet<OpmessageUsr>(0);
	private Set<Alerts> alertses = new HashSet<Alerts>(0);
	private Set<Acknowledges> acknowledgeses = new HashSet<Acknowledges>(0);
	private Set<UsersGroups> usersGroupses = new HashSet<UsersGroups>(0);
	private Set<UserHistory> userHistories = new HashSet<UserHistory>(0);

	public Users() {
	}

	public Users(long userid, String alias, String name, String surname, String passwd, String url, int autologin,
			int autologout, String lang, int refresh, int type, String theme, int attemptFailed, String attemptIp,
			int attemptClock, int rowsPerPage) {
		this.userid = userid;
		this.alias = alias;
		this.name = name;
		this.surname = surname;
		this.passwd = passwd;
		this.url = url;
		this.autologin = autologin;
		this.autologout = autologout;
		this.lang = lang;
		this.refresh = refresh;
		this.type = type;
		this.theme = theme;
		this.attemptFailed = attemptFailed;
		this.attemptIp = attemptIp;
		this.attemptClock = attemptClock;
		this.rowsPerPage = rowsPerPage;
	}

	public Users(long userid, String alias, String name, String surname, String passwd, String url, int autologin,
			int autologout, String lang, int refresh, int type, String theme, int attemptFailed, String attemptIp,
			int attemptClock, int rowsPerPage, Set<Profiles> profileses, Set<Auditlog> auditlogs,
			Set<Sessions> sessionses, Set<Media> medias, Set<OpmessageUsr> opmessageUsrs, Set<Alerts> alertses,
			Set<Acknowledges> acknowledgeses, Set<UsersGroups> usersGroupses, Set<UserHistory> userHistories) {
		this.userid = userid;
		this.alias = alias;
		this.name = name;
		this.surname = surname;
		this.passwd = passwd;
		this.url = url;
		this.autologin = autologin;
		this.autologout = autologout;
		this.lang = lang;
		this.refresh = refresh;
		this.type = type;
		this.theme = theme;
		this.attemptFailed = attemptFailed;
		this.attemptIp = attemptIp;
		this.attemptClock = attemptClock;
		this.rowsPerPage = rowsPerPage;
		this.profileses = profileses;
		this.auditlogs = auditlogs;
		this.sessionses = sessionses;
		this.medias = medias;
		this.opmessageUsrs = opmessageUsrs;
		this.alertses = alertses;
		this.acknowledgeses = acknowledgeses;
		this.usersGroupses = usersGroupses;
		this.userHistories = userHistories;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false)
	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	@Column(name = "alias", nullable = false, length = 100)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 100)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "passwd", nullable = false, length = 32)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "autologin", nullable = false)
	public int getAutologin() {
		return this.autologin;
	}

	public void setAutologin(int autologin) {
		this.autologin = autologin;
	}

	@Column(name = "autologout", nullable = false)
	public int getAutologout() {
		return this.autologout;
	}

	public void setAutologout(int autologout) {
		this.autologout = autologout;
	}

	@Column(name = "lang", nullable = false, length = 5)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "refresh", nullable = false)
	public int getRefresh() {
		return this.refresh;
	}

	public void setRefresh(int refresh) {
		this.refresh = refresh;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "theme", nullable = false, length = 128)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "attempt_failed", nullable = false)
	public int getAttemptFailed() {
		return this.attemptFailed;
	}

	public void setAttemptFailed(int attemptFailed) {
		this.attemptFailed = attemptFailed;
	}

	@Column(name = "attempt_ip", nullable = false, length = 39)
	public String getAttemptIp() {
		return this.attemptIp;
	}

	public void setAttemptIp(String attemptIp) {
		this.attemptIp = attemptIp;
	}

	@Column(name = "attempt_clock", nullable = false)
	public int getAttemptClock() {
		return this.attemptClock;
	}

	public void setAttemptClock(int attemptClock) {
		this.attemptClock = attemptClock;
	}

	@Column(name = "rows_per_page", nullable = false)
	public int getRowsPerPage() {
		return this.rowsPerPage;
	}

	public void setRowsPerPage(int rowsPerPage) {
		this.rowsPerPage = rowsPerPage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Profiles> getProfileses() {
		return this.profileses;
	}

	public void setProfileses(Set<Profiles> profileses) {
		this.profileses = profileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Auditlog> getAuditlogs() {
		return this.auditlogs;
	}

	public void setAuditlogs(Set<Auditlog> auditlogs) {
		this.auditlogs = auditlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Sessions> getSessionses() {
		return this.sessionses;
	}

	public void setSessionses(Set<Sessions> sessionses) {
		this.sessionses = sessionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<OpmessageUsr> getOpmessageUsrs() {
		return this.opmessageUsrs;
	}

	public void setOpmessageUsrs(Set<OpmessageUsr> opmessageUsrs) {
		this.opmessageUsrs = opmessageUsrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Alerts> getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set<Alerts> alertses) {
		this.alertses = alertses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Acknowledges> getAcknowledgeses() {
		return this.acknowledgeses;
	}

	public void setAcknowledgeses(Set<Acknowledges> acknowledgeses) {
		this.acknowledgeses = acknowledgeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UsersGroups> getUsersGroupses() {
		return this.usersGroupses;
	}

	public void setUsersGroupses(Set<UsersGroups> usersGroupses) {
		this.usersGroupses = usersGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserHistory> getUserHistories() {
		return this.userHistories;
	}

	public void setUserHistories(Set<UserHistory> userHistories) {
		this.userHistories = userHistories;
	}

}
