package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersGroups generated by hbm2java
 */
@Entity
@Table(name = "users_groups", catalog = "skycloud", uniqueConstraints = @UniqueConstraint(columnNames = { "usrgrpid",
		"userid" }))
public class UsersGroups implements java.io.Serializable {

	private long id;
	private Users users;
	private Usrgrp usrgrp;

	public UsersGroups() {
	}

	public UsersGroups(long id, Users users, Usrgrp usrgrp) {
		this.id = id;
		this.users = users;
		this.usrgrp = usrgrp;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usrgrpid", nullable = false)
	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

}
