package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usrgrp generated by hbm2java
 */
@Entity
@Table(name = "usrgrp", catalog = "skycloud")
public class Usrgrp implements java.io.Serializable {

	private long usrgrpid;
	private String name;
	private int guiAccess;
	private int usersStatus;
	private int debugMode;
	private Set<Rights> rightses = new HashSet<Rights>(0);
	private Set<Config> configs = new HashSet<Config>(0);
	private Set<Scripts> scriptses = new HashSet<Scripts>(0);
	private Set<OpmessageGrp> opmessageGrps = new HashSet<OpmessageGrp>(0);
	private Set<UsersGroups> usersGroupses = new HashSet<UsersGroups>(0);

	public Usrgrp() {
	}

	public Usrgrp(long usrgrpid, String name, int guiAccess, int usersStatus, int debugMode) {
		this.usrgrpid = usrgrpid;
		this.name = name;
		this.guiAccess = guiAccess;
		this.usersStatus = usersStatus;
		this.debugMode = debugMode;
	}

	public Usrgrp(long usrgrpid, String name, int guiAccess, int usersStatus, int debugMode, Set<Rights> rightses,
			Set<Config> configs, Set<Scripts> scriptses, Set<OpmessageGrp> opmessageGrps, Set<UsersGroups> usersGroupses) {
		this.usrgrpid = usrgrpid;
		this.name = name;
		this.guiAccess = guiAccess;
		this.usersStatus = usersStatus;
		this.debugMode = debugMode;
		this.rightses = rightses;
		this.configs = configs;
		this.scriptses = scriptses;
		this.opmessageGrps = opmessageGrps;
		this.usersGroupses = usersGroupses;
	}

	@Id
	@Column(name = "usrgrpid", unique = true, nullable = false)
	public long getUsrgrpid() {
		return this.usrgrpid;
	}

	public void setUsrgrpid(long usrgrpid) {
		this.usrgrpid = usrgrpid;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gui_access", nullable = false)
	public int getGuiAccess() {
		return this.guiAccess;
	}

	public void setGuiAccess(int guiAccess) {
		this.guiAccess = guiAccess;
	}

	@Column(name = "users_status", nullable = false)
	public int getUsersStatus() {
		return this.usersStatus;
	}

	public void setUsersStatus(int usersStatus) {
		this.usersStatus = usersStatus;
	}

	@Column(name = "debug_mode", nullable = false)
	public int getDebugMode() {
		return this.debugMode;
	}

	public void setDebugMode(int debugMode) {
		this.debugMode = debugMode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrgrp")
	public Set<Rights> getRightses() {
		return this.rightses;
	}

	public void setRightses(Set<Rights> rightses) {
		this.rightses = rightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrgrp")
	public Set<Config> getConfigs() {
		return this.configs;
	}

	public void setConfigs(Set<Config> configs) {
		this.configs = configs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrgrp")
	public Set<Scripts> getScriptses() {
		return this.scriptses;
	}

	public void setScriptses(Set<Scripts> scriptses) {
		this.scriptses = scriptses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrgrp")
	public Set<OpmessageGrp> getOpmessageGrps() {
		return this.opmessageGrps;
	}

	public void setOpmessageGrps(Set<OpmessageGrp> opmessageGrps) {
		this.opmessageGrps = opmessageGrps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrgrp")
	public Set<UsersGroups> getUsersGroupses() {
		return this.usersGroupses;
	}

	public void setUsersGroupses(Set<UsersGroups> usersGroupses) {
		this.usersGroupses = usersGroupses;
	}

}
