package com.skycloud.jkb.pojo.entity;

// Generated 2013-12-31 14:44:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Valuemaps generated by hbm2java
 */
@Entity
@Table(name = "valuemaps", catalog = "skycloud")
public class Valuemaps implements java.io.Serializable {

	private long valuemapid;
	private String name;
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<Mappings> mappingses = new HashSet<Mappings>(0);

	public Valuemaps() {
	}

	public Valuemaps(long valuemapid, String name) {
		this.valuemapid = valuemapid;
		this.name = name;
	}

	public Valuemaps(long valuemapid, String name, Set<Items> itemses, Set<Mappings> mappingses) {
		this.valuemapid = valuemapid;
		this.name = name;
		this.itemses = itemses;
		this.mappingses = mappingses;
	}

	@Id
	@Column(name = "valuemapid", unique = true, nullable = false)
	public long getValuemapid() {
		return this.valuemapid;
	}

	public void setValuemapid(long valuemapid) {
		this.valuemapid = valuemapid;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valuemaps")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valuemaps")
	public Set<Mappings> getMappingses() {
		return this.mappingses;
	}

	public void setMappingses(Set<Mappings> mappingses) {
		this.mappingses = mappingses;
	}

}
